/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CancellTreatmentDto,
  CompleteTreatmentDto,
  CreateCustomTreatmentDto,
  CreateTreatmentDto,
  TreatmentControllerFindAllByPatientParams,
  TreatmentControllerFindAllParams,
  TreatmentControllerUpdate200,
  TreatmentEntity,
  TreatmentRaginatedResponse,
  UpdateTreatmentDto,
} from '../../models';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

export const treatmentControllerCreate = (
  createTreatmentDto: CreateTreatmentDto,
  signal?: AbortSignal
) => {
  return apiInstance<TreatmentEntity[]>({
    url: `/api/treatments`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createTreatmentDto,
    signal,
  });
};

export const getTreatmentControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof treatmentControllerCreate>>,
    TError,
    { data: CreateTreatmentDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof treatmentControllerCreate>>,
  TError,
  { data: CreateTreatmentDto },
  TContext
> => {
  const mutationKey = ['treatmentControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof treatmentControllerCreate>>,
    { data: CreateTreatmentDto }
  > = (props) => {
    const { data } = props ?? {};

    return treatmentControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TreatmentControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerCreate>>
>;
export type TreatmentControllerCreateMutationBody = CreateTreatmentDto;
export type TreatmentControllerCreateMutationError = unknown;

export const useTreatmentControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof treatmentControllerCreate>>,
      TError,
      { data: CreateTreatmentDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof treatmentControllerCreate>>,
  TError,
  { data: CreateTreatmentDto },
  TContext
> => {
  const mutationOptions = getTreatmentControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const treatmentControllerFindAll = (
  params?: TreatmentControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<TreatmentRaginatedResponse>({
    url: `/api/treatments`,
    method: 'GET',
    params,
    signal,
  });
};

export const getTreatmentControllerFindAllQueryKey = (
  params?: TreatmentControllerFindAllParams
) => {
  return [`/api/treatments`, ...(params ? [params] : [])] as const;
};

export const getTreatmentControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof treatmentControllerFindAll>>,
  TError = unknown,
>(
  params?: TreatmentControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTreatmentControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof treatmentControllerFindAll>>> = ({
    signal,
  }) => treatmentControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof treatmentControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TreatmentControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerFindAll>>
>;
export type TreatmentControllerFindAllQueryError = unknown;

export function useTreatmentControllerFindAll<
  TData = Awaited<ReturnType<typeof treatmentControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | TreatmentControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof treatmentControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof treatmentControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTreatmentControllerFindAll<
  TData = Awaited<ReturnType<typeof treatmentControllerFindAll>>,
  TError = unknown,
>(
  params?: TreatmentControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof treatmentControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof treatmentControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTreatmentControllerFindAll<
  TData = Awaited<ReturnType<typeof treatmentControllerFindAll>>,
  TError = unknown,
>(
  params?: TreatmentControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTreatmentControllerFindAll<
  TData = Awaited<ReturnType<typeof treatmentControllerFindAll>>,
  TError = unknown,
>(
  params?: TreatmentControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTreatmentControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const treatmentControllerCreateCutom = (
  createCustomTreatmentDto: CreateCustomTreatmentDto,
  signal?: AbortSignal
) => {
  return apiInstance<TreatmentEntity[]>({
    url: `/api/treatments/custom`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createCustomTreatmentDto,
    signal,
  });
};

export const getTreatmentControllerCreateCutomMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof treatmentControllerCreateCutom>>,
    TError,
    { data: CreateCustomTreatmentDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof treatmentControllerCreateCutom>>,
  TError,
  { data: CreateCustomTreatmentDto },
  TContext
> => {
  const mutationKey = ['treatmentControllerCreateCutom'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof treatmentControllerCreateCutom>>,
    { data: CreateCustomTreatmentDto }
  > = (props) => {
    const { data } = props ?? {};

    return treatmentControllerCreateCutom(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TreatmentControllerCreateCutomMutationResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerCreateCutom>>
>;
export type TreatmentControllerCreateCutomMutationBody = CreateCustomTreatmentDto;
export type TreatmentControllerCreateCutomMutationError = unknown;

export const useTreatmentControllerCreateCutom = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof treatmentControllerCreateCutom>>,
      TError,
      { data: CreateCustomTreatmentDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof treatmentControllerCreateCutom>>,
  TError,
  { data: CreateCustomTreatmentDto },
  TContext
> => {
  const mutationOptions = getTreatmentControllerCreateCutomMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const treatmentControllerCreateByAdmin = (
  createCustomTreatmentDto: CreateCustomTreatmentDto,
  signal?: AbortSignal
) => {
  return apiInstance<TreatmentEntity[]>({
    url: `/api/treatments/admin`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createCustomTreatmentDto,
    signal,
  });
};

export const getTreatmentControllerCreateByAdminMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof treatmentControllerCreateByAdmin>>,
    TError,
    { data: CreateCustomTreatmentDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof treatmentControllerCreateByAdmin>>,
  TError,
  { data: CreateCustomTreatmentDto },
  TContext
> => {
  const mutationKey = ['treatmentControllerCreateByAdmin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof treatmentControllerCreateByAdmin>>,
    { data: CreateCustomTreatmentDto }
  > = (props) => {
    const { data } = props ?? {};

    return treatmentControllerCreateByAdmin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TreatmentControllerCreateByAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerCreateByAdmin>>
>;
export type TreatmentControllerCreateByAdminMutationBody = CreateCustomTreatmentDto;
export type TreatmentControllerCreateByAdminMutationError = unknown;

export const useTreatmentControllerCreateByAdmin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof treatmentControllerCreateByAdmin>>,
      TError,
      { data: CreateCustomTreatmentDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof treatmentControllerCreateByAdmin>>,
  TError,
  { data: CreateCustomTreatmentDto },
  TContext
> => {
  const mutationOptions = getTreatmentControllerCreateByAdminMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const treatmentControllerFindAllByPatient = (
  params?: TreatmentControllerFindAllByPatientParams,
  signal?: AbortSignal
) => {
  return apiInstance<TreatmentRaginatedResponse>({
    url: `/api/treatments/patient`,
    method: 'GET',
    params,
    signal,
  });
};

export const getTreatmentControllerFindAllByPatientQueryKey = (
  params?: TreatmentControllerFindAllByPatientParams
) => {
  return [`/api/treatments/patient`, ...(params ? [params] : [])] as const;
};

export const getTreatmentControllerFindAllByPatientQueryOptions = <
  TData = Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
  TError = unknown,
>(
  params?: TreatmentControllerFindAllByPatientParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTreatmentControllerFindAllByPatientQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>> = ({
    signal,
  }) => treatmentControllerFindAllByPatient(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TreatmentControllerFindAllByPatientQueryResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>
>;
export type TreatmentControllerFindAllByPatientQueryError = unknown;

export function useTreatmentControllerFindAllByPatient<
  TData = Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
  TError = unknown,
>(
  params: undefined | TreatmentControllerFindAllByPatientParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
          TError,
          Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTreatmentControllerFindAllByPatient<
  TData = Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
  TError = unknown,
>(
  params?: TreatmentControllerFindAllByPatientParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
          TError,
          Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTreatmentControllerFindAllByPatient<
  TData = Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
  TError = unknown,
>(
  params?: TreatmentControllerFindAllByPatientParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTreatmentControllerFindAllByPatient<
  TData = Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
  TError = unknown,
>(
  params?: TreatmentControllerFindAllByPatientParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindAllByPatient>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTreatmentControllerFindAllByPatientQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const treatmentControllerFindOneByPatient = (id: string, signal?: AbortSignal) => {
  return apiInstance<TreatmentEntity>({
    url: `/api/treatments/${id}/patient`,
    method: 'GET',
    signal,
  });
};

export const getTreatmentControllerFindOneByPatientQueryKey = (id?: string) => {
  return [`/api/treatments/${id}/patient`] as const;
};

export const getTreatmentControllerFindOneByPatientQueryOptions = <
  TData = Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTreatmentControllerFindOneByPatientQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>> = ({
    signal,
  }) => treatmentControllerFindOneByPatient(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TreatmentControllerFindOneByPatientQueryResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>
>;
export type TreatmentControllerFindOneByPatientQueryError = unknown;

export function useTreatmentControllerFindOneByPatient<
  TData = Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
          TError,
          Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTreatmentControllerFindOneByPatient<
  TData = Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
          TError,
          Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTreatmentControllerFindOneByPatient<
  TData = Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTreatmentControllerFindOneByPatient<
  TData = Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof treatmentControllerFindOneByPatient>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTreatmentControllerFindOneByPatientQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const treatmentControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<TreatmentEntity>({ url: `/api/treatments/${id}`, method: 'GET', signal });
};

export const getTreatmentControllerFindOneQueryKey = (id?: string) => {
  return [`/api/treatments/${id}`] as const;
};

export const getTreatmentControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof treatmentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTreatmentControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof treatmentControllerFindOne>>> = ({
    signal,
  }) => treatmentControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof treatmentControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TreatmentControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerFindOne>>
>;
export type TreatmentControllerFindOneQueryError = unknown;

export function useTreatmentControllerFindOne<
  TData = Awaited<ReturnType<typeof treatmentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof treatmentControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof treatmentControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTreatmentControllerFindOne<
  TData = Awaited<ReturnType<typeof treatmentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof treatmentControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof treatmentControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTreatmentControllerFindOne<
  TData = Awaited<ReturnType<typeof treatmentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTreatmentControllerFindOne<
  TData = Awaited<ReturnType<typeof treatmentControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof treatmentControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTreatmentControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const treatmentControllerUpdate = (id: string, updateTreatmentDto: UpdateTreatmentDto) => {
  return apiInstance<TreatmentControllerUpdate200>({
    url: `/api/treatments/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateTreatmentDto,
  });
};

export const getTreatmentControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof treatmentControllerUpdate>>,
    TError,
    { id: string; data: UpdateTreatmentDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof treatmentControllerUpdate>>,
  TError,
  { id: string; data: UpdateTreatmentDto },
  TContext
> => {
  const mutationKey = ['treatmentControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof treatmentControllerUpdate>>,
    { id: string; data: UpdateTreatmentDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return treatmentControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TreatmentControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerUpdate>>
>;
export type TreatmentControllerUpdateMutationBody = UpdateTreatmentDto;
export type TreatmentControllerUpdateMutationError = unknown;

export const useTreatmentControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof treatmentControllerUpdate>>,
      TError,
      { id: string; data: UpdateTreatmentDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof treatmentControllerUpdate>>,
  TError,
  { id: string; data: UpdateTreatmentDto },
  TContext
> => {
  const mutationOptions = getTreatmentControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const treatmentControllerRemove = (id: string) => {
  return apiInstance<void>({ url: `/api/treatments/${id}`, method: 'DELETE' });
};

export const getTreatmentControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof treatmentControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof treatmentControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['treatmentControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof treatmentControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return treatmentControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type TreatmentControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerRemove>>
>;

export type TreatmentControllerRemoveMutationError = unknown;

export const useTreatmentControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof treatmentControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof treatmentControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getTreatmentControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const treatmentControllerComplete = (
  id: string,
  completeTreatmentDto: CompleteTreatmentDto
) => {
  return apiInstance<TreatmentEntity>({
    url: `/api/treatments/${id}/complete`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: completeTreatmentDto,
  });
};

export const getTreatmentControllerCompleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof treatmentControllerComplete>>,
    TError,
    { id: string; data: CompleteTreatmentDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof treatmentControllerComplete>>,
  TError,
  { id: string; data: CompleteTreatmentDto },
  TContext
> => {
  const mutationKey = ['treatmentControllerComplete'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof treatmentControllerComplete>>,
    { id: string; data: CompleteTreatmentDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return treatmentControllerComplete(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TreatmentControllerCompleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerComplete>>
>;
export type TreatmentControllerCompleteMutationBody = CompleteTreatmentDto;
export type TreatmentControllerCompleteMutationError = unknown;

export const useTreatmentControllerComplete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof treatmentControllerComplete>>,
      TError,
      { id: string; data: CompleteTreatmentDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof treatmentControllerComplete>>,
  TError,
  { id: string; data: CompleteTreatmentDto },
  TContext
> => {
  const mutationOptions = getTreatmentControllerCompleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const treatmentControllerCancell = (
  id: string,
  cancellTreatmentDto: CancellTreatmentDto
) => {
  return apiInstance<void>({
    url: `/api/treatments/${id}/cancell`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: cancellTreatmentDto,
  });
};

export const getTreatmentControllerCancellMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof treatmentControllerCancell>>,
    TError,
    { id: string; data: CancellTreatmentDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof treatmentControllerCancell>>,
  TError,
  { id: string; data: CancellTreatmentDto },
  TContext
> => {
  const mutationKey = ['treatmentControllerCancell'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof treatmentControllerCancell>>,
    { id: string; data: CancellTreatmentDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return treatmentControllerCancell(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type TreatmentControllerCancellMutationResult = NonNullable<
  Awaited<ReturnType<typeof treatmentControllerCancell>>
>;
export type TreatmentControllerCancellMutationBody = CancellTreatmentDto;
export type TreatmentControllerCancellMutationError = unknown;

export const useTreatmentControllerCancell = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof treatmentControllerCancell>>,
      TError,
      { id: string; data: CancellTreatmentDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof treatmentControllerCancell>>,
  TError,
  { id: string; data: CancellTreatmentDto },
  TContext
> => {
  const mutationOptions = getTreatmentControllerCancellMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
