/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type AppointmentsControllerGetSubstitutableCanceledStatus =
  (typeof AppointmentsControllerGetSubstitutableCanceledStatus)[keyof typeof AppointmentsControllerGetSubstitutableCanceledStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppointmentsControllerGetSubstitutableCanceledStatus = {
  WAITING: 'WAITING',
  ACCEPTED: 'ACCEPTED',
  VISIT: 'VISIT',
  CANCELED: 'CANCELED',
  DELAYED: 'DELAYED',
  EMERGENCY: 'EMERGENCY',
} as const;
