/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type AppointmentsControllerDoctorAppointmentsStatus =
  (typeof AppointmentsControllerDoctorAppointmentsStatus)[keyof typeof AppointmentsControllerDoctorAppointmentsStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppointmentsControllerDoctorAppointmentsStatus = {
  WAITING: 'WAITING',
  ACCEPTED: 'ACCEPTED',
  VISIT: 'VISIT',
  CANCELED: 'CANCELED',
  DELAYED: 'DELAYED',
  EMERGENCY: 'EMERGENCY',
} as const;
