/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

/**
 * Reason for suspension (only DoctorLeave, AssistantLeave, PatientAbsent, UnitFailure, Other allowed)
 */
export type BulkSuspendAppointmentsDtoReason =
  (typeof BulkSuspendAppointmentsDtoReason)[keyof typeof BulkSuspendAppointmentsDtoReason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BulkSuspendAppointmentsDtoReason = {
  DoctorLeave: 'DoctorLeave',
  AssistantLeave: 'AssistantLeave',
  PatientAbsent: 'PatientAbsent',
  UnitFailure: 'UnitFailure',
  Other: 'Other',
} as const;
