/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { BulkCancelSuspendedAppointmentFailedDto } from './bulkCancelSuspendedAppointmentFailedDto';

export interface BulkCancelSuspendedAppointmentsResultDto {
  succeeded: string[];
  failed: BulkCancelSuspendedAppointmentFailedDto[];
  notFound: string[];
}
