/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CheckControllerFindMineSortType } from './checkControllerFindMineSortType';
import type { CheckControllerFindMineSortBy } from './checkControllerFindMineSortBy';

export type CheckControllerFindMineParams = {
  dueDateFrom?: string;
  dueDateTo?: string;
  sortType?: CheckControllerFindMineSortType;
  sortBy?: CheckControllerFindMineSortBy;
  bankName?: string;
  branch?: string;
  checkNumber?: string;
  userId?: string;
  isCleared?: boolean;
  page?: number;
  limit?: number;
};
