/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateMedicalSystemPriceDtoTreatmentType } from './createMedicalSystemPriceDtoTreatmentType';

export interface CreateMedicalSystemPriceDto {
  /** @minimum 0 */
  price: number;
  treatmentCategoryId: string;
  treatmentType: CreateMedicalSystemPriceDtoTreatmentType;
}
