/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateMedicalInfoDto } from './createMedicalInfoDto';
import type { CreateDentalInfoDto } from './createDentalInfoDto';
import type { CreateInsuranceInfoDto } from './createInsuranceInfoDto';
import type { CreateAdditionalInfoDto } from './createAdditionalInfoDto';

export interface CreateDocumentDto {
  job?: string;
  medicalInfo?: CreateMedicalInfoDto;
  dentalInfo?: CreateDentalInfoDto;
  insuranceInfo?: CreateInsuranceInfoDto[];
  additionalInfo?: CreateAdditionalInfoDto;
}
