/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateMedicalInfoDtoGender } from './createMedicalInfoDtoGender';

export interface CreateMedicalInfoDto {
  gender: CreateMedicalInfoDtoGender;
  isPregnant: boolean;
  specialDiseases?: string;
  allergyBackground?: string;
  medications?: string;
  surgeryHistory?: string;
  communicableDiseases?: string;
  drugSensitivity?: string;
}
