/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type CreateMultipleTreatmentPlansDtoType =
  (typeof CreateMultipleTreatmentPlansDtoType)[keyof typeof CreateMultipleTreatmentPlansDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMultipleTreatmentPlansDtoType = {
  SPECIALIZED: 'SPECIALIZED',
  NON_SPECIALIZED: 'NON_SPECIALIZED',
  HYBRID: 'HYBRID',
} as const;
