/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateSpecialDiscountDtoMethod } from './createSpecialDiscountDtoMethod';

export interface CreateSpecialDiscountDto {
  specialCriteria: string;
  /** @minimum 0 */
  fixedAmount: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  percentage: number;
  method: CreateSpecialDiscountDtoMethod;
}
