/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { DoctorTreatmentPlanControllerExportToExcelType } from './doctorTreatmentPlanControllerExportToExcelType';

export type DoctorTreatmentPlanControllerExportToExcelParams = {
  doctorId?: string;
  treatmentCategoryId?: string;
  name?: string;
  type?: DoctorTreatmentPlanControllerExportToExcelType;
  page?: number;
  limit?: number;
};
