/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type GoodControllerFindAllFilterIsActive =
  (typeof GoodControllerFindAllFilterIsActive)[keyof typeof GoodControllerFindAllFilterIsActive];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GoodControllerFindAllFilterIsActive = {
  true: 'true',
  false: 'false',
} as const;
