/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { LaboratoryControllerFindAllFilterStatus } from './laboratoryControllerFindAllFilterStatus';

export type LaboratoryControllerFindAllParams = {
  page?: number;
  limit?: number;
  search?: string;
  /**
   * Filter by name using operators like $eq, $gte, etc.
   */
  'filter.name'?: string;
  /**
   * Filter by code using operators like $eq, $gte, etc.
   */
  'filter.code'?: string;
  /**
   * Filter by nationalId using operators like $eq, $gte, etc.
   */
  'filter.nationalId'?: string;
  /**
   * Filter by registerationNumber using operators like $eq, $gte, etc.
   */
  'filter.registerationNumber'?: string;
  /**
   * Filter by phoneNumber using operators like $eq, $gte, etc.
   */
  'filter.phoneNumber'?: string;
  /**
   * Filter by status using operators like $eq, $gte, etc.
   */
  'filter.status'?: LaboratoryControllerFindAllFilterStatus;
  sortBy?: string[];
};
