/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type LabOrdersControllerFindAllSortType =
  (typeof LabOrdersControllerFindAllSortType)[keyof typeof LabOrdersControllerFindAllSortType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LabOrdersControllerFindAllSortType = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
