/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type MedicalSystemPriceResponseDtoTreatmentType =
  (typeof MedicalSystemPriceResponseDtoTreatmentType)[keyof typeof MedicalSystemPriceResponseDtoTreatmentType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MedicalSystemPriceResponseDtoTreatmentType = {
  SPECIALIZED: 'SPECIALIZED',
  NON_SPECIALIZED: 'NON_SPECIALIZED',
  HYBRID: 'HYBRID',
} as const;
