/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { PatientControllerFindDebtorPatientsSortType } from './patientControllerFindDebtorPatientsSortType';
import type { PatientControllerFindDebtorPatientsSortBy } from './patientControllerFindDebtorPatientsSortBy';

export type PatientControllerFindDebtorPatientsParams = {
  sortType?: PatientControllerFindDebtorPatientsSortType;
  sortBy?: PatientControllerFindDebtorPatientsSortBy;
  name?: string;
  page?: number;
  limit?: number;
};
