/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type RenewedTreatmentPlanControllerFindAllSortBy =
  (typeof RenewedTreatmentPlanControllerFindAllSortBy)[keyof typeof RenewedTreatmentPlanControllerFindAllSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RenewedTreatmentPlanControllerFindAllSortBy = {
  createdAt: 'createdAt',
} as const;
