/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type SpecialDiscountsControllerFindAllMethod =
  (typeof SpecialDiscountsControllerFindAllMethod)[keyof typeof SpecialDiscountsControllerFindAllMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpecialDiscountsControllerFindAllMethod = {
  FIXED: 'FIXED',
  PERCENTAGE: 'PERCENTAGE',
} as const;
