/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { SuspendAppointmentDtoReason } from './suspendAppointmentDtoReason';

export interface SuspendAppointmentDto {
  /** Reason for suspension (only DoctorLeave, AssistantLeave, PatientAbsent, UnitFailure, Other allowed for manual suspend) */
  reason: SuspendAppointmentDtoReason;
  /** Description (required if reason is Other) */
  description?: string;
}
