/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { SuspensionHistoryExpandedResponseDtoSuspensionReason } from './suspensionHistoryExpandedResponseDtoSuspensionReason';
import type { SuspensionHistoryExpandedResponseDtoRegisterType } from './suspensionHistoryExpandedResponseDtoRegisterType';
import type { ExpandedAppointmentSnapshotDto } from './expandedAppointmentSnapshotDto';

export interface SuspensionHistoryExpandedResponseDto {
  id: string;
  suspendedAt: string;
  suspensionReason: SuspensionHistoryExpandedResponseDtoSuspensionReason;
  /** @nullable */
  description: string | null;
  registerType: SuspensionHistoryExpandedResponseDtoRegisterType;
  oldAppointmentExpanded: ExpandedAppointmentSnapshotDto;
}
