/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { PaginationMetaDto } from './paginationMetaDto';
import type { PaginationLinksDto } from './paginationLinksDto';
import type { GroupedTreatmentPlanResponseDto } from './groupedTreatmentPlanResponseDto';

export interface TreatmentPlanGroupRaginatedResponse {
  meta: PaginationMetaDto;
  links: PaginationLinksDto;
  items: GroupedTreatmentPlanResponseDto[];
}
