/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { TreatmentPlanControllerFindAllSortType } from './treatmentPlanControllerFindAllSortType';
import type { TreatmentPlanControllerFindAllSortby } from './treatmentPlanControllerFindAllSortby';

export type TreatmentPlanControllerFindAllParams = {
  dentNameId?: string;
  assistantId?: string;
  paymentMethod?: string;
  categoryId?: string;
  doctorId?: string;
  patientId?: string;
  isHead?: boolean;
  isUnforseen?: boolean;
  isSelected?: boolean;
  sortType?: TreatmentPlanControllerFindAllSortType;
  sortby?: TreatmentPlanControllerFindAllSortby;
  page?: number;
  limit?: number;
};
