/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type TreatmentPlanControllerFindAllByUserSortType =
  (typeof TreatmentPlanControllerFindAllByUserSortType)[keyof typeof TreatmentPlanControllerFindAllByUserSortType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TreatmentPlanControllerFindAllByUserSortType = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
