/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type TreatMentCategoryControllerFindChildsType =
  (typeof TreatMentCategoryControllerFindChildsType)[keyof typeof TreatMentCategoryControllerFindChildsType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TreatMentCategoryControllerFindChildsType = {
  TREATMENT_HEADLINE: 'TREATMENT_HEADLINE',
  TREATMENT_DESCRIPTION: 'TREATMENT_DESCRIPTION',
  TREATMENT_TITLE: 'TREATMENT_TITLE',
  SHARED: 'SHARED',
} as const;
