/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type UpdateTreatmentPlanDtoStatus =
  (typeof UpdateTreatmentPlanDtoStatus)[keyof typeof UpdateTreatmentPlanDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateTreatmentPlanDtoStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_REVIEW: 'WAITING_FOR_REVIEW',
  SELECTED: 'SELECTED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
} as const;
