/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  BulkDeleteDto,
  PaginatedSmsResponse,
  SaveDraftDto,
  SaveGroupDrafts,
  SendDraftDto,
  SendGroupDraftDto,
  SendGroupSmsDto,
  SendSmsDto,
  SmsControllerFindAllParams,
  SmsControllerSaveGroupDrafts201Item,
  SmsControllerSendGroupDrafts201Item,
  SmsControllerSendGroupSms201Item,
  SmsEntity,
} from '../../models1';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: read_sms
 */
export const smsControllerFindAll = (params?: SmsControllerFindAllParams, signal?: AbortSignal) => {
  return apiInstance<PaginatedSmsResponse>({ url: `/api/sms`, method: 'GET', params, signal });
};

export const getSmsControllerFindAllQueryKey = (params?: SmsControllerFindAllParams) => {
  return [`/api/sms`, ...(params ? [params] : [])] as const;
};

export const getSmsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof smsControllerFindAll>>,
  TError = unknown,
>(
  params?: SmsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof smsControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getSmsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof smsControllerFindAll>>> = ({ signal }) =>
    smsControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof smsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SmsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerFindAll>>
>;
export type SmsControllerFindAllQueryError = unknown;

export function useSmsControllerFindAll<
  TData = Awaited<ReturnType<typeof smsControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | SmsControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof smsControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof smsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof smsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSmsControllerFindAll<
  TData = Awaited<ReturnType<typeof smsControllerFindAll>>,
  TError = unknown,
>(
  params?: SmsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof smsControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof smsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof smsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useSmsControllerFindAll<
  TData = Awaited<ReturnType<typeof smsControllerFindAll>>,
  TError = unknown,
>(
  params?: SmsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof smsControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_sms
 */

export function useSmsControllerFindAll<
  TData = Awaited<ReturnType<typeof smsControllerFindAll>>,
  TError = unknown,
>(
  params?: SmsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof smsControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getSmsControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: create_sms
 */
export const smsControllerSend = (sendSmsDto: SendSmsDto, signal?: AbortSignal) => {
  return apiInstance<SmsEntity>({
    url: `/api/sms/send`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendSmsDto,
    signal,
  });
};

export const getSmsControllerSendMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerSend>>,
    TError,
    { data: SendSmsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerSend>>,
  TError,
  { data: SendSmsDto },
  TContext
> => {
  const mutationKey = ['smsControllerSend'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerSend>>,
    { data: SendSmsDto }
  > = (props) => {
    const { data } = props ?? {};

    return smsControllerSend(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerSendMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerSend>>
>;
export type SmsControllerSendMutationBody = SendSmsDto;
export type SmsControllerSendMutationError = unknown;

/**
 * @summary required permisson: create_sms
 */
export const useSmsControllerSend = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerSend>>,
      TError,
      { data: SendSmsDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerSend>>,
  TError,
  { data: SendSmsDto },
  TContext
> => {
  const mutationOptions = getSmsControllerSendMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const smsControllerSendGroupSms = (
  sendGroupSmsDto: SendGroupSmsDto,
  signal?: AbortSignal
) => {
  return apiInstance<SmsControllerSendGroupSms201Item[]>({
    url: `/api/sms/send/group`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendGroupSmsDto,
    signal,
  });
};

export const getSmsControllerSendGroupSmsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerSendGroupSms>>,
    TError,
    { data: SendGroupSmsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerSendGroupSms>>,
  TError,
  { data: SendGroupSmsDto },
  TContext
> => {
  const mutationKey = ['smsControllerSendGroupSms'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerSendGroupSms>>,
    { data: SendGroupSmsDto }
  > = (props) => {
    const { data } = props ?? {};

    return smsControllerSendGroupSms(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerSendGroupSmsMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerSendGroupSms>>
>;
export type SmsControllerSendGroupSmsMutationBody = SendGroupSmsDto;
export type SmsControllerSendGroupSmsMutationError = unknown;

export const useSmsControllerSendGroupSms = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerSendGroupSms>>,
      TError,
      { data: SendGroupSmsDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerSendGroupSms>>,
  TError,
  { data: SendGroupSmsDto },
  TContext
> => {
  const mutationOptions = getSmsControllerSendGroupSmsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: create_sms
 */
export const smsControllerSendQuick = (sendSmsDto: SendSmsDto, signal?: AbortSignal) => {
  return apiInstance<SmsEntity>({
    url: `/api/sms/sendQuick`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendSmsDto,
    signal,
  });
};

export const getSmsControllerSendQuickMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerSendQuick>>,
    TError,
    { data: SendSmsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerSendQuick>>,
  TError,
  { data: SendSmsDto },
  TContext
> => {
  const mutationKey = ['smsControllerSendQuick'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerSendQuick>>,
    { data: SendSmsDto }
  > = (props) => {
    const { data } = props ?? {};

    return smsControllerSendQuick(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerSendQuickMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerSendQuick>>
>;
export type SmsControllerSendQuickMutationBody = SendSmsDto;
export type SmsControllerSendQuickMutationError = unknown;

/**
 * @summary required permisson: create_sms
 */
export const useSmsControllerSendQuick = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerSendQuick>>,
      TError,
      { data: SendSmsDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerSendQuick>>,
  TError,
  { data: SendSmsDto },
  TContext
> => {
  const mutationOptions = getSmsControllerSendQuickMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: create_sms
 */
export const smsControllerSaveDraft = (saveDraftDto: SaveDraftDto, signal?: AbortSignal) => {
  return apiInstance<SmsEntity>({
    url: `/api/sms/save-draft-sms`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: saveDraftDto,
    signal,
  });
};

export const getSmsControllerSaveDraftMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerSaveDraft>>,
    TError,
    { data: SaveDraftDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerSaveDraft>>,
  TError,
  { data: SaveDraftDto },
  TContext
> => {
  const mutationKey = ['smsControllerSaveDraft'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerSaveDraft>>,
    { data: SaveDraftDto }
  > = (props) => {
    const { data } = props ?? {};

    return smsControllerSaveDraft(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerSaveDraftMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerSaveDraft>>
>;
export type SmsControllerSaveDraftMutationBody = SaveDraftDto;
export type SmsControllerSaveDraftMutationError = unknown;

/**
 * @summary required permisson: create_sms
 */
export const useSmsControllerSaveDraft = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerSaveDraft>>,
      TError,
      { data: SaveDraftDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerSaveDraft>>,
  TError,
  { data: SaveDraftDto },
  TContext
> => {
  const mutationOptions = getSmsControllerSaveDraftMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const smsControllerSaveGroupDrafts = (
  saveGroupDrafts: SaveGroupDrafts,
  signal?: AbortSignal
) => {
  return apiInstance<SmsControllerSaveGroupDrafts201Item[]>({
    url: `/api/sms/save-group-drafts`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: saveGroupDrafts,
    signal,
  });
};

export const getSmsControllerSaveGroupDraftsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerSaveGroupDrafts>>,
    TError,
    { data: SaveGroupDrafts },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerSaveGroupDrafts>>,
  TError,
  { data: SaveGroupDrafts },
  TContext
> => {
  const mutationKey = ['smsControllerSaveGroupDrafts'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerSaveGroupDrafts>>,
    { data: SaveGroupDrafts }
  > = (props) => {
    const { data } = props ?? {};

    return smsControllerSaveGroupDrafts(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerSaveGroupDraftsMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerSaveGroupDrafts>>
>;
export type SmsControllerSaveGroupDraftsMutationBody = SaveGroupDrafts;
export type SmsControllerSaveGroupDraftsMutationError = unknown;

export const useSmsControllerSaveGroupDrafts = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerSaveGroupDrafts>>,
      TError,
      { data: SaveGroupDrafts },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerSaveGroupDrafts>>,
  TError,
  { data: SaveGroupDrafts },
  TContext
> => {
  const mutationOptions = getSmsControllerSaveGroupDraftsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_sms
 */
export const smsControllerSendDraft = (sendDraftDto: SendDraftDto, signal?: AbortSignal) => {
  return apiInstance<SmsEntity>({
    url: `/api/sms/send-draft-sms`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendDraftDto,
    signal,
  });
};

export const getSmsControllerSendDraftMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerSendDraft>>,
    TError,
    { data: SendDraftDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerSendDraft>>,
  TError,
  { data: SendDraftDto },
  TContext
> => {
  const mutationKey = ['smsControllerSendDraft'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerSendDraft>>,
    { data: SendDraftDto }
  > = (props) => {
    const { data } = props ?? {};

    return smsControllerSendDraft(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerSendDraftMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerSendDraft>>
>;
export type SmsControllerSendDraftMutationBody = SendDraftDto;
export type SmsControllerSendDraftMutationError = unknown;

/**
 * @summary required permisson: update_sms
 */
export const useSmsControllerSendDraft = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerSendDraft>>,
      TError,
      { data: SendDraftDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerSendDraft>>,
  TError,
  { data: SendDraftDto },
  TContext
> => {
  const mutationOptions = getSmsControllerSendDraftMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const smsControllerSendGroupDrafts = (
  sendGroupDraftDto: SendGroupDraftDto,
  signal?: AbortSignal
) => {
  return apiInstance<SmsControllerSendGroupDrafts201Item[]>({
    url: `/api/sms/send/group-drafts`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: sendGroupDraftDto,
    signal,
  });
};

export const getSmsControllerSendGroupDraftsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerSendGroupDrafts>>,
    TError,
    { data: SendGroupDraftDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerSendGroupDrafts>>,
  TError,
  { data: SendGroupDraftDto },
  TContext
> => {
  const mutationKey = ['smsControllerSendGroupDrafts'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerSendGroupDrafts>>,
    { data: SendGroupDraftDto }
  > = (props) => {
    const { data } = props ?? {};

    return smsControllerSendGroupDrafts(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerSendGroupDraftsMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerSendGroupDrafts>>
>;
export type SmsControllerSendGroupDraftsMutationBody = SendGroupDraftDto;
export type SmsControllerSendGroupDraftsMutationError = unknown;

export const useSmsControllerSendGroupDrafts = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerSendGroupDrafts>>,
      TError,
      { data: SendGroupDraftDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerSendGroupDrafts>>,
  TError,
  { data: SendGroupDraftDto },
  TContext
> => {
  const mutationOptions = getSmsControllerSendGroupDraftsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const smsControllerBulkDelete = (bulkDeleteDto: BulkDeleteDto) => {
  return apiInstance<void>({
    url: `/api/sms/bulk`,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    data: bulkDeleteDto,
  });
};

export const getSmsControllerBulkDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerBulkDelete>>,
    TError,
    { data: BulkDeleteDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerBulkDelete>>,
  TError,
  { data: BulkDeleteDto },
  TContext
> => {
  const mutationKey = ['smsControllerBulkDelete'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerBulkDelete>>,
    { data: BulkDeleteDto }
  > = (props) => {
    const { data } = props ?? {};

    return smsControllerBulkDelete(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerBulkDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerBulkDelete>>
>;
export type SmsControllerBulkDeleteMutationBody = BulkDeleteDto;
export type SmsControllerBulkDeleteMutationError = unknown;

export const useSmsControllerBulkDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerBulkDelete>>,
      TError,
      { data: BulkDeleteDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerBulkDelete>>,
  TError,
  { data: BulkDeleteDto },
  TContext
> => {
  const mutationOptions = getSmsControllerBulkDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const smsControllerCancelScheduledSms = (id: string) => {
  return apiInstance<SmsEntity>({ url: `/api/sms/${id}/cancel`, method: 'PATCH' });
};

export const getSmsControllerCancelScheduledSmsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerCancelScheduledSms>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerCancelScheduledSms>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['smsControllerCancelScheduledSms'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerCancelScheduledSms>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return smsControllerCancelScheduledSms(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerCancelScheduledSmsMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerCancelScheduledSms>>
>;

export type SmsControllerCancelScheduledSmsMutationError = unknown;

export const useSmsControllerCancelScheduledSms = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerCancelScheduledSms>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerCancelScheduledSms>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getSmsControllerCancelScheduledSmsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const smsControllerSendScheduled = (id: string) => {
  return apiInstance<SmsEntity>({ url: `/api/sms/${id}/sendschedule`, method: 'PATCH' });
};

export const getSmsControllerSendScheduledMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof smsControllerSendScheduled>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof smsControllerSendScheduled>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['smsControllerSendScheduled'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof smsControllerSendScheduled>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return smsControllerSendScheduled(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type SmsControllerSendScheduledMutationResult = NonNullable<
  Awaited<ReturnType<typeof smsControllerSendScheduled>>
>;

export type SmsControllerSendScheduledMutationError = unknown;

export const useSmsControllerSendScheduled = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof smsControllerSendScheduled>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof smsControllerSendScheduled>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getSmsControllerSendScheduledMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
