/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateVisitSlotDto,
  UpdateVisitSlotDto,
  VisitSlot,
  VisitSlotControllerFindAllParams,
} from '../../models2';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: create_visit_slot
 */
export const visitSlotControllerCreate = (
  createVisitSlotDto: CreateVisitSlotDto,
  signal?: AbortSignal
) => {
  return apiInstance<VisitSlot>({
    url: `/api/visit-slots`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createVisitSlotDto,
    signal,
  });
};

export const getVisitSlotControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof visitSlotControllerCreate>>,
    TError,
    { data: CreateVisitSlotDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof visitSlotControllerCreate>>,
  TError,
  { data: CreateVisitSlotDto },
  TContext
> => {
  const mutationKey = ['visitSlotControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof visitSlotControllerCreate>>,
    { data: CreateVisitSlotDto }
  > = (props) => {
    const { data } = props ?? {};

    return visitSlotControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VisitSlotControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof visitSlotControllerCreate>>
>;
export type VisitSlotControllerCreateMutationBody = CreateVisitSlotDto;
export type VisitSlotControllerCreateMutationError = unknown;

/**
 * @summary required permisson: create_visit_slot
 */
export const useVisitSlotControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof visitSlotControllerCreate>>,
      TError,
      { data: CreateVisitSlotDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof visitSlotControllerCreate>>,
  TError,
  { data: CreateVisitSlotDto },
  TContext
> => {
  const mutationOptions = getVisitSlotControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_visit_slot
 */
export const visitSlotControllerFindAll = (
  params?: VisitSlotControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<void>({ url: `/api/visit-slots`, method: 'GET', params, signal });
};

export const getVisitSlotControllerFindAllQueryKey = (
  params?: VisitSlotControllerFindAllParams
) => {
  return [`/api/visit-slots`, ...(params ? [params] : [])] as const;
};

export const getVisitSlotControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof visitSlotControllerFindAll>>,
  TError = unknown,
>(
  params?: VisitSlotControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVisitSlotControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof visitSlotControllerFindAll>>> = ({
    signal,
  }) => visitSlotControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof visitSlotControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VisitSlotControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof visitSlotControllerFindAll>>
>;
export type VisitSlotControllerFindAllQueryError = unknown;

export function useVisitSlotControllerFindAll<
  TData = Awaited<ReturnType<typeof visitSlotControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | VisitSlotControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitSlotControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof visitSlotControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVisitSlotControllerFindAll<
  TData = Awaited<ReturnType<typeof visitSlotControllerFindAll>>,
  TError = unknown,
>(
  params?: VisitSlotControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitSlotControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof visitSlotControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVisitSlotControllerFindAll<
  TData = Awaited<ReturnType<typeof visitSlotControllerFindAll>>,
  TError = unknown,
>(
  params?: VisitSlotControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_visit_slot
 */

export function useVisitSlotControllerFindAll<
  TData = Awaited<ReturnType<typeof visitSlotControllerFindAll>>,
  TError = unknown,
>(
  params?: VisitSlotControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVisitSlotControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_visit_slot
 */
export const visitSlotControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<VisitSlot>({ url: `/api/visit-slots/${id}`, method: 'GET', signal });
};

export const getVisitSlotControllerFindOneQueryKey = (id?: string) => {
  return [`/api/visit-slots/${id}`] as const;
};

export const getVisitSlotControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof visitSlotControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVisitSlotControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof visitSlotControllerFindOne>>> = ({
    signal,
  }) => visitSlotControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof visitSlotControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VisitSlotControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof visitSlotControllerFindOne>>
>;
export type VisitSlotControllerFindOneQueryError = unknown;

export function useVisitSlotControllerFindOne<
  TData = Awaited<ReturnType<typeof visitSlotControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitSlotControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof visitSlotControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVisitSlotControllerFindOne<
  TData = Awaited<ReturnType<typeof visitSlotControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitSlotControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof visitSlotControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVisitSlotControllerFindOne<
  TData = Awaited<ReturnType<typeof visitSlotControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_visit_slot
 */

export function useVisitSlotControllerFindOne<
  TData = Awaited<ReturnType<typeof visitSlotControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof visitSlotControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVisitSlotControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_visit_slot
 */
export const visitSlotControllerUpdate = (id: string, updateVisitSlotDto: UpdateVisitSlotDto) => {
  return apiInstance<VisitSlot>({
    url: `/api/visit-slots/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateVisitSlotDto,
  });
};

export const getVisitSlotControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof visitSlotControllerUpdate>>,
    TError,
    { id: string; data: UpdateVisitSlotDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof visitSlotControllerUpdate>>,
  TError,
  { id: string; data: UpdateVisitSlotDto },
  TContext
> => {
  const mutationKey = ['visitSlotControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof visitSlotControllerUpdate>>,
    { id: string; data: UpdateVisitSlotDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return visitSlotControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VisitSlotControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof visitSlotControllerUpdate>>
>;
export type VisitSlotControllerUpdateMutationBody = UpdateVisitSlotDto;
export type VisitSlotControllerUpdateMutationError = unknown;

/**
 * @summary required permisson: update_visit_slot
 */
export const useVisitSlotControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof visitSlotControllerUpdate>>,
      TError,
      { id: string; data: UpdateVisitSlotDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof visitSlotControllerUpdate>>,
  TError,
  { id: string; data: UpdateVisitSlotDto },
  TContext
> => {
  const mutationOptions = getVisitSlotControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: delete_visit_slot
 */
export const visitSlotControllerDelete = (id: string) => {
  return apiInstance<boolean>({ url: `/api/visit-slots/${id}`, method: 'DELETE' });
};

export const getVisitSlotControllerDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof visitSlotControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof visitSlotControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['visitSlotControllerDelete'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof visitSlotControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return visitSlotControllerDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type VisitSlotControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof visitSlotControllerDelete>>
>;

export type VisitSlotControllerDeleteMutationError = unknown;

/**
 * @summary required permisson: delete_visit_slot
 */
export const useVisitSlotControllerDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof visitSlotControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof visitSlotControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getVisitSlotControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
