/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateShelfDto,
  PaginatedShelfResponse,
  Shelf,
  ShelfControllerFindAllParams,
  ShelfControllerSearchParams,
  ShelfControllerUpdate200,
  UpdateShelfDto,
} from '../../models1';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: create_shelf
 */
export const shelfControllerCreate = (createShelfDto: CreateShelfDto, signal?: AbortSignal) => {
  return apiInstance<Shelf>({
    url: `/api/shelfs`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createShelfDto,
    signal,
  });
};

export const getShelfControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shelfControllerCreate>>,
    TError,
    { data: CreateShelfDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shelfControllerCreate>>,
  TError,
  { data: CreateShelfDto },
  TContext
> => {
  const mutationKey = ['shelfControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shelfControllerCreate>>,
    { data: CreateShelfDto }
  > = (props) => {
    const { data } = props ?? {};

    return shelfControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShelfControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof shelfControllerCreate>>
>;
export type ShelfControllerCreateMutationBody = CreateShelfDto;
export type ShelfControllerCreateMutationError = unknown;

/**
 * @summary required permisson: create_shelf
 */
export const useShelfControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shelfControllerCreate>>,
      TError,
      { data: CreateShelfDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof shelfControllerCreate>>,
  TError,
  { data: CreateShelfDto },
  TContext
> => {
  const mutationOptions = getShelfControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_shelf
 */
export const shelfControllerFindAll = (
  params?: ShelfControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<PaginatedShelfResponse>({ url: `/api/shelfs`, method: 'GET', params, signal });
};

export const getShelfControllerFindAllQueryKey = (params?: ShelfControllerFindAllParams) => {
  return [`/api/shelfs`, ...(params ? [params] : [])] as const;
};

export const getShelfControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof shelfControllerFindAll>>,
  TError = unknown,
>(
  params?: ShelfControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShelfControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shelfControllerFindAll>>> = ({ signal }) =>
    shelfControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shelfControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShelfControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof shelfControllerFindAll>>
>;
export type ShelfControllerFindAllQueryError = unknown;

export function useShelfControllerFindAll<
  TData = Awaited<ReturnType<typeof shelfControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | ShelfControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof shelfControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof shelfControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useShelfControllerFindAll<
  TData = Awaited<ReturnType<typeof shelfControllerFindAll>>,
  TError = unknown,
>(
  params?: ShelfControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof shelfControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof shelfControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useShelfControllerFindAll<
  TData = Awaited<ReturnType<typeof shelfControllerFindAll>>,
  TError = unknown,
>(
  params?: ShelfControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_shelf
 */

export function useShelfControllerFindAll<
  TData = Awaited<ReturnType<typeof shelfControllerFindAll>>,
  TError = unknown,
>(
  params?: ShelfControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getShelfControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_shelf
 */
export const shelfControllerSearch = (
  params?: ShelfControllerSearchParams,
  signal?: AbortSignal
) => {
  return apiInstance<Shelf[]>({ url: `/api/shelfs/search`, method: 'GET', params, signal });
};

export const getShelfControllerSearchQueryKey = (params?: ShelfControllerSearchParams) => {
  return [`/api/shelfs/search`, ...(params ? [params] : [])] as const;
};

export const getShelfControllerSearchQueryOptions = <
  TData = Awaited<ReturnType<typeof shelfControllerSearch>>,
  TError = unknown,
>(
  params?: ShelfControllerSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerSearch>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShelfControllerSearchQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shelfControllerSearch>>> = ({ signal }) =>
    shelfControllerSearch(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shelfControllerSearch>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShelfControllerSearchQueryResult = NonNullable<
  Awaited<ReturnType<typeof shelfControllerSearch>>
>;
export type ShelfControllerSearchQueryError = unknown;

export function useShelfControllerSearch<
  TData = Awaited<ReturnType<typeof shelfControllerSearch>>,
  TError = unknown,
>(
  params: undefined | ShelfControllerSearchParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerSearch>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof shelfControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof shelfControllerSearch>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useShelfControllerSearch<
  TData = Awaited<ReturnType<typeof shelfControllerSearch>>,
  TError = unknown,
>(
  params?: ShelfControllerSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerSearch>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof shelfControllerSearch>>,
          TError,
          Awaited<ReturnType<typeof shelfControllerSearch>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useShelfControllerSearch<
  TData = Awaited<ReturnType<typeof shelfControllerSearch>>,
  TError = unknown,
>(
  params?: ShelfControllerSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerSearch>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_shelf
 */

export function useShelfControllerSearch<
  TData = Awaited<ReturnType<typeof shelfControllerSearch>>,
  TError = unknown,
>(
  params?: ShelfControllerSearchParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerSearch>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getShelfControllerSearchQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: create_shelf
 */
export const shelfControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<Shelf>({ url: `/api/shelfs/${id}`, method: 'GET', signal });
};

export const getShelfControllerFindOneQueryKey = (id?: string) => {
  return [`/api/shelfs/${id}`] as const;
};

export const getShelfControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof shelfControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getShelfControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof shelfControllerFindOne>>> = ({ signal }) =>
    shelfControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof shelfControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ShelfControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof shelfControllerFindOne>>
>;
export type ShelfControllerFindOneQueryError = unknown;

export function useShelfControllerFindOne<
  TData = Awaited<ReturnType<typeof shelfControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof shelfControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof shelfControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useShelfControllerFindOne<
  TData = Awaited<ReturnType<typeof shelfControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof shelfControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof shelfControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useShelfControllerFindOne<
  TData = Awaited<ReturnType<typeof shelfControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: create_shelf
 */

export function useShelfControllerFindOne<
  TData = Awaited<ReturnType<typeof shelfControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof shelfControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getShelfControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_shelf
 */
export const shelfControllerUpdate = (id: string, updateShelfDto: UpdateShelfDto) => {
  return apiInstance<ShelfControllerUpdate200>({
    url: `/api/shelfs/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateShelfDto,
  });
};

export const getShelfControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shelfControllerUpdate>>,
    TError,
    { id: string; data: UpdateShelfDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shelfControllerUpdate>>,
  TError,
  { id: string; data: UpdateShelfDto },
  TContext
> => {
  const mutationKey = ['shelfControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shelfControllerUpdate>>,
    { id: string; data: UpdateShelfDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return shelfControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShelfControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof shelfControllerUpdate>>
>;
export type ShelfControllerUpdateMutationBody = UpdateShelfDto;
export type ShelfControllerUpdateMutationError = unknown;

/**
 * @summary required permisson: update_shelf
 */
export const useShelfControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shelfControllerUpdate>>,
      TError,
      { id: string; data: UpdateShelfDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof shelfControllerUpdate>>,
  TError,
  { id: string; data: UpdateShelfDto },
  TContext
> => {
  const mutationOptions = getShelfControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: delete_shelf
 */
export const shelfControllerRemove = (id: string) => {
  return apiInstance<void>({ url: `/api/shelfs/${id}`, method: 'DELETE' });
};

export const getShelfControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof shelfControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof shelfControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['shelfControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof shelfControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return shelfControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type ShelfControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof shelfControllerRemove>>
>;

export type ShelfControllerRemoveMutationError = unknown;

/**
 * @summary required permisson: delete_shelf
 */
export const useShelfControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof shelfControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof shelfControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getShelfControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
