/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateUnitOrderDto,
  PaginatedUnitOrdersResponse,
  UnitOrdersControllerFindAllParams,
  UnitOrdersEntity,
  UpdateUnitOrderDto,
} from '../../models1';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: create_unit_order
 */
export const unitOrdersControllerCreate = (
  createUnitOrderDto: CreateUnitOrderDto,
  signal?: AbortSignal
) => {
  return apiInstance<UnitOrdersEntity>({
    url: `/api/unit-orders`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createUnitOrderDto,
    signal,
  });
};

export const getUnitOrdersControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unitOrdersControllerCreate>>,
    TError,
    { data: CreateUnitOrderDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unitOrdersControllerCreate>>,
  TError,
  { data: CreateUnitOrderDto },
  TContext
> => {
  const mutationKey = ['unitOrdersControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unitOrdersControllerCreate>>,
    { data: CreateUnitOrderDto }
  > = (props) => {
    const { data } = props ?? {};

    return unitOrdersControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnitOrdersControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof unitOrdersControllerCreate>>
>;
export type UnitOrdersControllerCreateMutationBody = CreateUnitOrderDto;
export type UnitOrdersControllerCreateMutationError = unknown;

/**
 * @summary required permisson: create_unit_order
 */
export const useUnitOrdersControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unitOrdersControllerCreate>>,
      TError,
      { data: CreateUnitOrderDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof unitOrdersControllerCreate>>,
  TError,
  { data: CreateUnitOrderDto },
  TContext
> => {
  const mutationOptions = getUnitOrdersControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_unit_order
 */
export const unitOrdersControllerFindAll = (
  params?: UnitOrdersControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<PaginatedUnitOrdersResponse>({
    url: `/api/unit-orders`,
    method: 'GET',
    params,
    signal,
  });
};

export const getUnitOrdersControllerFindAllQueryKey = (
  params?: UnitOrdersControllerFindAllParams
) => {
  return [`/api/unit-orders`, ...(params ? [params] : [])] as const;
};

export const getUnitOrdersControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindAll>>,
  TError = unknown,
>(
  params?: UnitOrdersControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUnitOrdersControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof unitOrdersControllerFindAll>>> = ({
    signal,
  }) => unitOrdersControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof unitOrdersControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UnitOrdersControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof unitOrdersControllerFindAll>>
>;
export type UnitOrdersControllerFindAllQueryError = unknown;

export function useUnitOrdersControllerFindAll<
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | UnitOrdersControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof unitOrdersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof unitOrdersControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUnitOrdersControllerFindAll<
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindAll>>,
  TError = unknown,
>(
  params?: UnitOrdersControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof unitOrdersControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof unitOrdersControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUnitOrdersControllerFindAll<
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindAll>>,
  TError = unknown,
>(
  params?: UnitOrdersControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_unit_order
 */

export function useUnitOrdersControllerFindAll<
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindAll>>,
  TError = unknown,
>(
  params?: UnitOrdersControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUnitOrdersControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_unit_order
 */
export const unitOrdersControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<UnitOrdersEntity>({ url: `/api/unit-orders/${id}`, method: 'GET', signal });
};

export const getUnitOrdersControllerFindOneQueryKey = (id?: string) => {
  return [`/api/unit-orders/${id}`] as const;
};

export const getUnitOrdersControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUnitOrdersControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof unitOrdersControllerFindOne>>> = ({
    signal,
  }) => unitOrdersControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof unitOrdersControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UnitOrdersControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof unitOrdersControllerFindOne>>
>;
export type UnitOrdersControllerFindOneQueryError = unknown;

export function useUnitOrdersControllerFindOne<
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof unitOrdersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof unitOrdersControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUnitOrdersControllerFindOne<
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof unitOrdersControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof unitOrdersControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUnitOrdersControllerFindOne<
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_unit_order
 */

export function useUnitOrdersControllerFindOne<
  TData = Awaited<ReturnType<typeof unitOrdersControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof unitOrdersControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUnitOrdersControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_unit_order
 */
export const unitOrdersControllerUpdate = (id: string, updateUnitOrderDto: UpdateUnitOrderDto) => {
  return apiInstance<void>({
    url: `/api/unit-orders/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateUnitOrderDto,
  });
};

export const getUnitOrdersControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unitOrdersControllerUpdate>>,
    TError,
    { id: string; data: UpdateUnitOrderDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unitOrdersControllerUpdate>>,
  TError,
  { id: string; data: UpdateUnitOrderDto },
  TContext
> => {
  const mutationKey = ['unitOrdersControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unitOrdersControllerUpdate>>,
    { id: string; data: UpdateUnitOrderDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return unitOrdersControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnitOrdersControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof unitOrdersControllerUpdate>>
>;
export type UnitOrdersControllerUpdateMutationBody = UpdateUnitOrderDto;
export type UnitOrdersControllerUpdateMutationError = unknown;

/**
 * @summary required permisson: update_unit_order
 */
export const useUnitOrdersControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unitOrdersControllerUpdate>>,
      TError,
      { id: string; data: UpdateUnitOrderDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof unitOrdersControllerUpdate>>,
  TError,
  { id: string; data: UpdateUnitOrderDto },
  TContext
> => {
  const mutationOptions = getUnitOrdersControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: delete_unit_order
 */
export const unitOrdersControllerRemove = (id: string) => {
  return apiInstance<void>({ url: `/api/unit-orders/${id}`, method: 'DELETE' });
};

export const getUnitOrdersControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof unitOrdersControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof unitOrdersControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['unitOrdersControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof unitOrdersControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return unitOrdersControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type UnitOrdersControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof unitOrdersControllerRemove>>
>;

export type UnitOrdersControllerRemoveMutationError = unknown;

/**
 * @summary required permisson: delete_unit_order
 */
export const useUnitOrdersControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof unitOrdersControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof unitOrdersControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getUnitOrdersControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
