/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type AppointmentStatus = (typeof AppointmentStatus)[keyof typeof AppointmentStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppointmentStatus = {
  WAITING: 'WAITING',
  ACCEPTED: 'ACCEPTED',
  VISIT: 'VISIT',
  CANCELED: 'CANCELED',
  DELAYED: 'DELAYED',
  EMERGENCY: 'EMERGENCY',
} as const;
