/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { Personnel } from './personnel';

export interface AttendanceEntity {
  date: string;
  enterTime: string;
  exitTime: string;
  personnelId: string;
  personnel: Personnel;
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
