/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { ChatRoomControllerFindMineSortType } from './chatRoomControllerFindMineSortType';
import type { ChatRoomControllerFindMineSortBy } from './chatRoomControllerFindMineSortBy';

export type ChatRoomControllerFindMineParams = {
  sortType?: ChatRoomControllerFindMineSortType;
  sortBy?: ChatRoomControllerFindMineSortBy;
  page?: number;
  limit?: number;
};
