/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateGoodArrivalDepratureDtoType } from './createGoodArrivalDepratureDtoType';

export interface CreateGoodArrivalDepratureDto {
  type: CreateGoodArrivalDepratureDtoType;
  description: string;
  /** @minimum 1 */
  quantity: number;
  goodId: string;
  wareHouseId: string;
  personnelId: string;
  expDate: string;
  /** @minimum 1 */
  price: number;
}
