/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type CreateProsAndConsDtoRelatedEntity =
  (typeof CreateProsAndConsDtoRelatedEntity)[keyof typeof CreateProsAndConsDtoRelatedEntity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProsAndConsDtoRelatedEntity = {
  doctor: 'doctor',
  patient: 'patient',
  personnel: 'personnel',
} as const;
