/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateCustomTreatmentDtoVerificationVideo } from './createCustomTreatmentDtoVerificationVideo';
import type { CreateCustomTreatmentDtoStatus } from './createCustomTreatmentDtoStatus';

export interface CreateCustomTreatmentDto {
  description?: string;
  invoiceId?: string;
  treatmentPlanId: string;
  parentId?: string;
  fingerprint?: string;
  assistantId?: string;
  verification_video: CreateCustomTreatmentDtoVerificationVideo;
  treatmentPrice: string;
  payment?: string;
  status?: CreateCustomTreatmentDtoStatus;
  doctorId?: string;
  ignorePayment?: boolean;
  allowDoctor?: boolean;
}
