/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAdditionalInfoDtoStressLevel } from './createAdditionalInfoDtoStressLevel';

export interface CreateAdditionalInfoDto {
  stressLevel?: CreateAdditionalInfoDtoStressLevel;
  specialRequests?: string;
}
