/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type CreateProsAndConsDtoType =
  (typeof CreateProsAndConsDtoType)[keyof typeof CreateProsAndConsDtoType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateProsAndConsDtoType = {
  Positive: 'Positive',
  Negative: 'Negative',
} as const;
