/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export interface CreateTreatmentCategoryDto {
  name: string;
  persianName?: string;
  description: string;
  parentId?: string;
  needsLab?: boolean;
  isUnforeseen?: boolean;
  /** @minimum 1 */
  order: number;
  code: string;
}
