/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { CreateInvoiceItemDto } from './createInvoiceItemDto';

export interface CreateInvoiceDto {
  items: CreateInvoiceItemDto[];
  date: string;
  totalPriceWithoutSupport: number;
  totalPercentageSupport: number;
  totalFixedAmountSupport: number;
  totalPayable: number;
  patientId: string;
  InsuranceInfoId: string;
  paymentGuaranteeId: string;
  referralDiscountId: string;
}
