/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { TreatmentPlanEntity } from './treatmentPlanEntity';
import type { LaboratoryOrderView } from './laboratoryOrderView';

export interface DentName {
  rowNumber: number;
  permanentUniversal: string;
  primaryUniversal: string;
  altPrimaryUniversal: string;
  permanentFDI: string;
  primaryFDI: string;
  permanentPalmer: string;
  primaryPalmer: string;
  treatmentPlans: TreatmentPlanEntity[];
  laboratoryOrderViews: LaboratoryOrderView[];
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
