/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { DiscountsControllerFindAllMethod } from './discountsControllerFindAllMethod';

export type DiscountsControllerFindAllParams = {
  title?: string;
  provider?: string;
  startDate?: string;
  endDate?: string;
  method?: DiscountsControllerFindAllMethod;
  treatmentCategoryId?: string;
  isGeneral?: boolean;
  page?: number;
  limit?: number;
};
