/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type GiftCodeControllerFindMineParams = {
  page?: number;
  limit?: number;
  search?: string;
  /**
   * Filter by type using operators like $eq, $gte, etc.
   */
  'filter.type'?: string;
  sortBy?: string[];
};
