/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { InsuranceCategoryEntity } from './insuranceCategoryEntity';
import type { Patient } from './patient';

export interface InsuranceInfo {
  insuranceNumber: string;
  expirationDate: string;
  dentalCoverage: boolean;
  maxSupport: number;
  insuranceCategory: InsuranceCategoryEntity;
  insuranceCategoryId: string;
  patient: Patient;
  patientId: string;
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
