/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type LabLoanGoodsControllerFindAllSortType =
  (typeof LabLoanGoodsControllerFindAllSortType)[keyof typeof LabLoanGoodsControllerFindAllSortType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LabLoanGoodsControllerFindAllSortType = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
