/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type LaboratoryOrderViewOrderStatus =
  (typeof LaboratoryOrderViewOrderStatus)[keyof typeof LaboratoryOrderViewOrderStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LaboratoryOrderViewOrderStatus = {
  PENDING: 'PENDING',
  WAITING_FOR_SCAN: 'WAITING_FOR_SCAN',
  SCANNED: 'SCANNED',
  READYTOSEND: 'READYTOSEND',
  SENTBYCLINIC: 'SENTBYCLINIC',
  RECIVEDBYLAB: 'RECIVEDBYLAB',
  INPROCCESS: 'INPROCCESS',
  REORDERD: 'REORDERD',
  MANUFATURED: 'MANUFATURED',
  SENTBYLAB: 'SENTBYLAB',
  RECEIVED_BYCLINIC: 'RECEIVED_BYCLINIC',
  PLACED_IN_SHELF: 'PLACED_IN_SHELF',
  RECEIVED_BY_ASSISTANT: 'RECEIVED_BY_ASSISTANT',
  DELIVERED_TO_PATIENT: 'DELIVERED_TO_PATIENT',
} as const;
