/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type ManufactureTypesControllerFindAllType =
  (typeof ManufactureTypesControllerFindAllType)[keyof typeof ManufactureTypesControllerFindAllType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ManufactureTypesControllerFindAllType = {
  FIXED: 'FIXED',
  PORTABLE: 'PORTABLE',
} as const;
