/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type MiscellaneousExpenseControllerFindAllSortType =
  (typeof MiscellaneousExpenseControllerFindAllSortType)[keyof typeof MiscellaneousExpenseControllerFindAllSortType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MiscellaneousExpenseControllerFindAllSortType = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
