/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type MiscellaneousExpenseControllerFindDebtOfPatientSortBy =
  (typeof MiscellaneousExpenseControllerFindDebtOfPatientSortBy)[keyof typeof MiscellaneousExpenseControllerFindDebtOfPatientSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MiscellaneousExpenseControllerFindDebtOfPatientSortBy = {
  amount: 'amount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;
