/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { NotificationDelivery } from './notificationDelivery';

export interface Notification {
  event: string;
  message: string;
  payload: string;
  deliveryStatus: NotificationDelivery[];
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
