/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { NotificationRoom } from './notificationRoom';
import type { Notification } from './notification';
import type { NotificationDeliveryStatus } from './notificationDeliveryStatus';

export interface NotificationDelivery {
  room: NotificationRoom;
  notification: Notification;
  status: NotificationDeliveryStatus;
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
