/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { Position } from './position';
import type { User } from './user';
import type { DoctorEntity } from './doctorEntity';
import type { IrregularScheduleEntity } from './irregularScheduleEntity';
import type { AttendanceEntity } from './attendanceEntity';
import type { Appointment } from './appointment';
import type { Section } from './section';
import type { UnitOrdersEntity } from './unitOrdersEntity';
import type { ReferralDiscount } from './referralDiscount';

export interface Personnel {
  position: Position;
  salary: number;
  resume: string;
  userInfo: User;
  personnelNumber: string;
  doctor: DoctorEntity;
  irregularSchedules: IrregularScheduleEntity[];
  attendances: AttendanceEntity[];
  appointments: Appointment[];
  managedSections: Section[];
  sections: Section[];
  receivedOrders: UnitOrdersEntity[];
  issuedReferralDiscounts: ReferralDiscount[];
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
