/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { InsuranceCategoryEntity } from './insuranceCategoryEntity';
import type { TreatmentCategoryEntity } from './treatmentCategoryEntity';

export interface Price {
  price: number;
  supportPercentage: number;
  supportAmount: number;
  insuranceCategory: InsuranceCategoryEntity;
  insuranceCategoryId: string;
  treatmentCategory: TreatmentCategoryEntity;
  treatmentCategoryId: string;
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
