/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export interface SaveFingerprintDto {
  /** @minItems 1 */
  fingerprintData: number[];
}
