/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { TreatmentEntityStatus } from './treatmentEntityStatus';
import type { TreatmentPlanEntity } from './treatmentPlanEntity';
import type { TreatmentEntity as __TreatmentEntity } from './treatmentEntity';
import type { DoctorEntity } from './doctorEntity';
import type { Personnel } from './personnel';
import type { SurveyEntity } from './surveyEntity';

export interface TreatmentEntity {
  description: string;
  treatmentPrice: string;
  payment: string;
  invoiceId: string;
  fingerprint: string;
  verification_video: string;
  status: TreatmentEntityStatus;
  treatmentPlan: TreatmentPlanEntity;
  childs: TreatmentEntity[];
  parent: __TreatmentEntity;
  parentId: string;
  doctor: DoctorEntity;
  doctorId: string;
  assistant: Personnel;
  assistantId: string;
  surveys: SurveyEntity[];
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
