/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { Unit } from './unit';

export interface UnitEquipment {
  name: string;
  quantity: number;
  unit: Unit;
  unitId: string;
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
