/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export interface UpdateUnitConsumableGoodsDto {
  /**
   * @minLength 1
   * @maxLength 255
   */
  name?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  latinName?: string;
  description?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  code?: string;
  /** @minimum 0 */
  orderPoint?: number;
  /**
   * @minLength 1
   * @maxLength 255
   */
  barcode?: string;
  /**
   * @minLength 1
   * @maxLength 255
   */
  categoryIdentifier?: string;
  unitId?: string;
}
