/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { UpdateReferralDiscountDtoStatus } from './updateReferralDiscountDtoStatus';
import type { UpdateReferralDiscountDtoMethod } from './updateReferralDiscountDtoMethod';

export interface UpdateReferralDiscountDto {
  patientId?: string;
  personnelId?: string;
  treatmentplanId?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  percentageAmount?: number;
  fixedAmount?: number;
  maxDiscountAmount?: number;
  description?: string;
  status?: UpdateReferralDiscountDtoStatus;
  method: UpdateReferralDiscountDtoMethod;
}
