/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { CreateAddressDto } from './createAddressDto';
import type { CreateClinicWorkScheduleDto } from './createClinicWorkScheduleDto';

export interface UpdateClinicInfoDto {
  /**
   * Name of the clinic
   * @maxLength 50
   */
  name?: string;
  /** Name of the clinic manager */
  managerName?: string;
  /** clinic code */
  code?: string;
  /** List of  clinic phone numbers */
  phoneNumbers?: string[];
  /** Clinic address information */
  address?: CreateAddressDto;
  /** Clinic work schedule */
  workSchedule?: CreateClinicWorkScheduleDto[];
}
