/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type UpdateReferralDiscountDtoMethod =
  (typeof UpdateReferralDiscountDtoMethod)[keyof typeof UpdateReferralDiscountDtoMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateReferralDiscountDtoMethod = {
  FIXED: 'FIXED',
  PERCENTAGE: 'PERCENTAGE',
} as const;
