/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */

export type UserControllerFindAllParams = {
  roleName?: string;
  advancedSearch?: boolean;
  userName?: string;
  email?: string;
  phoneNumber?: string;
  name?: string;
  nationalCode?: string;
  birthDate?: string;
  page?: number;
  limit?: number;
};
