/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { Wallet } from './wallet';
import type { WalletTransactionType } from './walletTransactionType';
import type { WalletTransactionStatus } from './walletTransactionStatus';
import type { PaidTreatmentPlan } from './paidTreatmentPlan';

export interface WalletTransaction {
  amount: number;
  fromWallet: Wallet;
  fromWalletId: string;
  toWallet: Wallet;
  toWalletId: string;
  type: WalletTransactionType;
  description: string;
  status: WalletTransactionStatus;
  paidTreatmentPlan: PaidTreatmentPlan;
  id: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
  creatorId: string;
}
