/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import type { WarehouseControllerFindAllStatus } from './warehouseControllerFindAllStatus';

export type WarehouseControllerFindAllParams = {
  title?: string;
  code?: string;
  managerId?: string;
  status?: WarehouseControllerFindAllStatus;
  page?: number;
  limit?: number;
};
