/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateVacationByAdminDto,
  CreateVacationDto,
  PaginatedVacationResponse,
  RejectVacationDto,
  UpdateVacationDto,
  VacationControllerFindAllParams,
  VacationControllerFindMieParams,
  VacationEntity,
} from '../../models2';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: read_vacation
 */
export const vacationControllerFindAll = (
  params?: VacationControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<PaginatedVacationResponse>({
    url: `/api/vacations`,
    method: 'GET',
    params,
    signal,
  });
};

export const getVacationControllerFindAllQueryKey = (params?: VacationControllerFindAllParams) => {
  return [`/api/vacations`, ...(params ? [params] : [])] as const;
};

export const getVacationControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof vacationControllerFindAll>>,
  TError = unknown,
>(
  params?: VacationControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVacationControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof vacationControllerFindAll>>> = ({
    signal,
  }) => vacationControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof vacationControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VacationControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerFindAll>>
>;
export type VacationControllerFindAllQueryError = unknown;

export function useVacationControllerFindAll<
  TData = Awaited<ReturnType<typeof vacationControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | VacationControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vacationControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof vacationControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVacationControllerFindAll<
  TData = Awaited<ReturnType<typeof vacationControllerFindAll>>,
  TError = unknown,
>(
  params?: VacationControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vacationControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof vacationControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVacationControllerFindAll<
  TData = Awaited<ReturnType<typeof vacationControllerFindAll>>,
  TError = unknown,
>(
  params?: VacationControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_vacation
 */

export function useVacationControllerFindAll<
  TData = Awaited<ReturnType<typeof vacationControllerFindAll>>,
  TError = unknown,
>(
  params?: VacationControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVacationControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: request_vacation
 */
export const vacationControllerCreate = (
  createVacationDto: CreateVacationDto,
  signal?: AbortSignal
) => {
  return apiInstance<VacationEntity>({
    url: `/api/vacations`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createVacationDto,
    signal,
  });
};

export const getVacationControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vacationControllerCreate>>,
    TError,
    { data: CreateVacationDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vacationControllerCreate>>,
  TError,
  { data: CreateVacationDto },
  TContext
> => {
  const mutationKey = ['vacationControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vacationControllerCreate>>,
    { data: CreateVacationDto }
  > = (props) => {
    const { data } = props ?? {};

    return vacationControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VacationControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerCreate>>
>;
export type VacationControllerCreateMutationBody = CreateVacationDto;
export type VacationControllerCreateMutationError = unknown;

/**
 * @summary required permisson: request_vacation
 */
export const useVacationControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vacationControllerCreate>>,
      TError,
      { data: CreateVacationDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vacationControllerCreate>>,
  TError,
  { data: CreateVacationDto },
  TContext
> => {
  const mutationOptions = getVacationControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: create_vacation
 */
export const vacationControllerCreateByAdmin = (
  createVacationByAdminDto: CreateVacationByAdminDto,
  signal?: AbortSignal
) => {
  return apiInstance<void>({
    url: `/api/vacations/by-admin`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createVacationByAdminDto,
    signal,
  });
};

export const getVacationControllerCreateByAdminMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vacationControllerCreateByAdmin>>,
    TError,
    { data: CreateVacationByAdminDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vacationControllerCreateByAdmin>>,
  TError,
  { data: CreateVacationByAdminDto },
  TContext
> => {
  const mutationKey = ['vacationControllerCreateByAdmin'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vacationControllerCreateByAdmin>>,
    { data: CreateVacationByAdminDto }
  > = (props) => {
    const { data } = props ?? {};

    return vacationControllerCreateByAdmin(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VacationControllerCreateByAdminMutationResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerCreateByAdmin>>
>;
export type VacationControllerCreateByAdminMutationBody = CreateVacationByAdminDto;
export type VacationControllerCreateByAdminMutationError = unknown;

/**
 * @summary required permisson: create_vacation
 */
export const useVacationControllerCreateByAdmin = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vacationControllerCreateByAdmin>>,
      TError,
      { data: CreateVacationByAdminDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vacationControllerCreateByAdmin>>,
  TError,
  { data: CreateVacationByAdminDto },
  TContext
> => {
  const mutationOptions = getVacationControllerCreateByAdminMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_vacation
 */
export const vacationControllerCancel = (id: string) => {
  return apiInstance<void>({ url: `/api/vacations/cancel/${id}`, method: 'PATCH' });
};

export const getVacationControllerCancelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vacationControllerCancel>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vacationControllerCancel>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['vacationControllerCancel'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vacationControllerCancel>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return vacationControllerCancel(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type VacationControllerCancelMutationResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerCancel>>
>;

export type VacationControllerCancelMutationError = unknown;

/**
 * @summary required permisson: update_vacation
 */
export const useVacationControllerCancel = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vacationControllerCancel>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vacationControllerCancel>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getVacationControllerCancelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_vacation
 */
export const vacationControllerAccept = (id: string) => {
  return apiInstance<void>({ url: `/api/vacations/accept/${id}`, method: 'PATCH' });
};

export const getVacationControllerAcceptMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vacationControllerAccept>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vacationControllerAccept>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['vacationControllerAccept'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vacationControllerAccept>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return vacationControllerAccept(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type VacationControllerAcceptMutationResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerAccept>>
>;

export type VacationControllerAcceptMutationError = unknown;

/**
 * @summary required permisson: update_vacation
 */
export const useVacationControllerAccept = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vacationControllerAccept>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vacationControllerAccept>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getVacationControllerAcceptMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_vacation
 */
export const vacationControllerReject = (id: string, rejectVacationDto: RejectVacationDto) => {
  return apiInstance<void>({
    url: `/api/vacations/reject/${id}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: rejectVacationDto,
  });
};

export const getVacationControllerRejectMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vacationControllerReject>>,
    TError,
    { id: string; data: RejectVacationDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vacationControllerReject>>,
  TError,
  { id: string; data: RejectVacationDto },
  TContext
> => {
  const mutationKey = ['vacationControllerReject'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vacationControllerReject>>,
    { id: string; data: RejectVacationDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return vacationControllerReject(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VacationControllerRejectMutationResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerReject>>
>;
export type VacationControllerRejectMutationBody = RejectVacationDto;
export type VacationControllerRejectMutationError = unknown;

/**
 * @summary required permisson: update_vacation
 */
export const useVacationControllerReject = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vacationControllerReject>>,
      TError,
      { id: string; data: RejectVacationDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vacationControllerReject>>,
  TError,
  { id: string; data: RejectVacationDto },
  TContext
> => {
  const mutationOptions = getVacationControllerRejectMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const vacationControllerFindMie = (
  params?: VacationControllerFindMieParams,
  signal?: AbortSignal
) => {
  return apiInstance<PaginatedVacationResponse>({
    url: `/api/vacations/mine`,
    method: 'GET',
    params,
    signal,
  });
};

export const getVacationControllerFindMieQueryKey = (params?: VacationControllerFindMieParams) => {
  return [`/api/vacations/mine`, ...(params ? [params] : [])] as const;
};

export const getVacationControllerFindMieQueryOptions = <
  TData = Awaited<ReturnType<typeof vacationControllerFindMie>>,
  TError = unknown,
>(
  params?: VacationControllerFindMieParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindMie>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVacationControllerFindMieQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof vacationControllerFindMie>>> = ({
    signal,
  }) => vacationControllerFindMie(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof vacationControllerFindMie>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VacationControllerFindMieQueryResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerFindMie>>
>;
export type VacationControllerFindMieQueryError = unknown;

export function useVacationControllerFindMie<
  TData = Awaited<ReturnType<typeof vacationControllerFindMie>>,
  TError = unknown,
>(
  params: undefined | VacationControllerFindMieParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindMie>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vacationControllerFindMie>>,
          TError,
          Awaited<ReturnType<typeof vacationControllerFindMie>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVacationControllerFindMie<
  TData = Awaited<ReturnType<typeof vacationControllerFindMie>>,
  TError = unknown,
>(
  params?: VacationControllerFindMieParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindMie>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vacationControllerFindMie>>,
          TError,
          Awaited<ReturnType<typeof vacationControllerFindMie>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVacationControllerFindMie<
  TData = Awaited<ReturnType<typeof vacationControllerFindMie>>,
  TError = unknown,
>(
  params?: VacationControllerFindMieParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindMie>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useVacationControllerFindMie<
  TData = Awaited<ReturnType<typeof vacationControllerFindMie>>,
  TError = unknown,
>(
  params?: VacationControllerFindMieParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindMie>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVacationControllerFindMieQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_vacation
 */
export const vacationControllerAdminCancel = (id: string) => {
  return apiInstance<void>({ url: `/api/vacations/admin/cancel/${id}`, method: 'PATCH' });
};

export const getVacationControllerAdminCancelMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vacationControllerAdminCancel>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vacationControllerAdminCancel>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['vacationControllerAdminCancel'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vacationControllerAdminCancel>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return vacationControllerAdminCancel(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type VacationControllerAdminCancelMutationResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerAdminCancel>>
>;

export type VacationControllerAdminCancelMutationError = unknown;

/**
 * @summary required permisson: update_vacation
 */
export const useVacationControllerAdminCancel = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vacationControllerAdminCancel>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vacationControllerAdminCancel>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getVacationControllerAdminCancelMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_vacation
 */
export const vacationControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<VacationEntity>({ url: `/api/vacations/${id}`, method: 'GET', signal });
};

export const getVacationControllerFindOneQueryKey = (id?: string) => {
  return [`/api/vacations/${id}`] as const;
};

export const getVacationControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof vacationControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVacationControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof vacationControllerFindOne>>> = ({
    signal,
  }) => vacationControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof vacationControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VacationControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerFindOne>>
>;
export type VacationControllerFindOneQueryError = unknown;

export function useVacationControllerFindOne<
  TData = Awaited<ReturnType<typeof vacationControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof vacationControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof vacationControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVacationControllerFindOne<
  TData = Awaited<ReturnType<typeof vacationControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof vacationControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof vacationControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVacationControllerFindOne<
  TData = Awaited<ReturnType<typeof vacationControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_vacation
 */

export function useVacationControllerFindOne<
  TData = Awaited<ReturnType<typeof vacationControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vacationControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVacationControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_vacation
 */
export const vacationControllerUpdate = (id: string, updateVacationDto: UpdateVacationDto) => {
  return apiInstance<void>({
    url: `/api/vacations/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateVacationDto,
  });
};

export const getVacationControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vacationControllerUpdate>>,
    TError,
    { id: string; data: UpdateVacationDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vacationControllerUpdate>>,
  TError,
  { id: string; data: UpdateVacationDto },
  TContext
> => {
  const mutationKey = ['vacationControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vacationControllerUpdate>>,
    { id: string; data: UpdateVacationDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return vacationControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VacationControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerUpdate>>
>;
export type VacationControllerUpdateMutationBody = UpdateVacationDto;
export type VacationControllerUpdateMutationError = unknown;

/**
 * @summary required permisson: update_vacation
 */
export const useVacationControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vacationControllerUpdate>>,
      TError,
      { id: string; data: UpdateVacationDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vacationControllerUpdate>>,
  TError,
  { id: string; data: UpdateVacationDto },
  TContext
> => {
  const mutationOptions = getVacationControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const vacationControllerUpdateMine = (id: string, updateVacationDto: UpdateVacationDto) => {
  return apiInstance<void>({
    url: `/api/vacations/mine/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateVacationDto,
  });
};

export const getVacationControllerUpdateMineMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vacationControllerUpdateMine>>,
    TError,
    { id: string; data: UpdateVacationDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vacationControllerUpdateMine>>,
  TError,
  { id: string; data: UpdateVacationDto },
  TContext
> => {
  const mutationKey = ['vacationControllerUpdateMine'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vacationControllerUpdateMine>>,
    { id: string; data: UpdateVacationDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return vacationControllerUpdateMine(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VacationControllerUpdateMineMutationResult = NonNullable<
  Awaited<ReturnType<typeof vacationControllerUpdateMine>>
>;
export type VacationControllerUpdateMineMutationBody = UpdateVacationDto;
export type VacationControllerUpdateMineMutationError = unknown;

export const useVacationControllerUpdateMine = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vacationControllerUpdateMine>>,
      TError,
      { id: string; data: UpdateVacationDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof vacationControllerUpdateMine>>,
  TError,
  { id: string; data: UpdateVacationDto },
  TContext
> => {
  const mutationOptions = getVacationControllerUpdateMineMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
