/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type AuditLogItemDtoEntity =
  (typeof AuditLogItemDtoEntity)[keyof typeof AuditLogItemDtoEntity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditLogItemDtoEntity = {
  APPOINTMENT: 'APPOINTMENT',
  PATIENT: 'PATIENT',
  TREATMENT_PLAN: 'TREATMENT_PLAN',
  TREATMENT: 'TREATMENT',
} as const;
