/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type AuditRecordHistoryItemDtoOperation = typeof AuditRecordHistoryItemDtoOperation[keyof typeof AuditRecordHistoryItemDtoOperation];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditRecordHistoryItemDtoOperation = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
} as const;
