/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type CreatePaymentGuaranteeDtoStatus =
  (typeof CreatePaymentGuaranteeDtoStatus)[keyof typeof CreatePaymentGuaranteeDtoStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreatePaymentGuaranteeDtoStatus = {
  WAITING: 'WAITING',
  CONFIRMED_BY_PERSONNEL: 'CONFIRMED_BY_PERSONNEL',
  REJECTED_BY_PERSONNEL: 'REJECTED_BY_PERSONNEL',
  CONFIRMED: 'CONFIRMED',
  CANCELED: 'CANCELED',
} as const;
