/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export interface DetachPersonnelDto {
  sectionId: string;
  personnelIds: string[];
}
