/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { DoctorTreatmentPerformanceReportControllerDoctorTreatmentPerformanceExcelSortType } from './doctorTreatmentPerformanceReportControllerDoctorTreatmentPerformanceExcelSortType';

export type DoctorTreatmentPerformanceReportControllerDoctorTreatmentPerformanceExcelParams = {
sortType?: DoctorTreatmentPerformanceReportControllerDoctorTreatmentPerformanceExcelSortType;
patientId?: string;
treatmentCategoryId?: string;
treatmentId?: string;
treatmentStepId?: string;
doctorId?: string;
fromDate?: string;
toDate?: string;
};
