/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { FundTransferDtoTransferType } from './fundTransferDtoTransferType';

export interface FundTransferDto {
  /** @minimum 1 */
  amount: number;
  fromWalletId: string;
  toWalletId: string;
  userDescription?: string;
  transferType: FundTransferDtoTransferType;
}
