/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { InvoiceControllerFindAllPaymentMethod } from './invoiceControllerFindAllPaymentMethod';
import type { InvoiceControllerFindAllSortType } from './invoiceControllerFindAllSortType';
import type { InvoiceControllerFindAllSortBy } from './invoiceControllerFindAllSortBy';

export type InvoiceControllerFindAllParams = {
  invoiceNumber?: string;
  patientId?: string;
  date?: string;
  paymentMethod?: InvoiceControllerFindAllPaymentMethod;
  sortType?: InvoiceControllerFindAllSortType;
  sortBy?: InvoiceControllerFindAllSortBy;
  page?: number;
  limit?: number;
};
