/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type InvoiceControllerFindMineSortType =
  (typeof InvoiceControllerFindMineSortType)[keyof typeof InvoiceControllerFindMineSortType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceControllerFindMineSortType = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
