/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { InvoiceControllerFindOneSortType } from './invoiceControllerFindOneSortType';
import type { InvoiceControllerFindOneSortby } from './invoiceControllerFindOneSortby';
import type { InvoiceControllerFindOnePaymentMethod } from './invoiceControllerFindOnePaymentMethod';

export type InvoiceControllerFindOneParams = {
  sortType?: InvoiceControllerFindOneSortType;
  sortby?: InvoiceControllerFindOneSortby;
  paymentMethod?: InvoiceControllerFindOnePaymentMethod;
};
