/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export interface LoanPaidTreatmentPlanReportItemDto {
  id: string;
  date: string;
  patientName: string;
  patientDocNumber: string;
  nationalCode: string;
  doctorName: string;
  categoryName: string;
  treatmentTitle: string;
  toothNumber: string;
  amount: number;
  loanAmount: number;
}
