/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { LoanControllerFindLoansByPatientIdAdminSortType } from './loanControllerFindLoansByPatientIdAdminSortType';
import type { LoanControllerFindLoansByPatientIdAdminStatus } from './loanControllerFindLoansByPatientIdAdminStatus';

export type LoanControllerFindLoansByPatientIdAdminParams = {
  sortType?: LoanControllerFindLoansByPatientIdAdminSortType;
  sortBy?: string;
  name?: string;
  /**
   * @minimum 1
   */
  requestedAmount?: number;
  /**
   * @minimum 1
   */
  acceptedAmount?: number;
  consultant?: string;
  bankRepresent?: string;
  status?: LoanControllerFindLoansByPatientIdAdminStatus;
  patientId?: string;
  page?: number;
  limit?: number;
};
