/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type PatientRegistrationReportControllerPatientRegistrationReportGender =
  (typeof PatientRegistrationReportControllerPatientRegistrationReportGender)[keyof typeof PatientRegistrationReportControllerPatientRegistrationReportGender];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatientRegistrationReportControllerPatientRegistrationReportGender = {
  Male: 'Male',
  Female: 'Female',
} as const;
