/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { PaymentGuaranteeControllerReferredFilterStatus } from './paymentGuaranteeControllerReferredFilterStatus';
import type { PaymentGuaranteeControllerReferredFilterIsPremium } from './paymentGuaranteeControllerReferredFilterIsPremium';

export type PaymentGuaranteeControllerReferredParams = {
  page?: number;
  limit?: number;
  search?: string;
  /**
   * Filter by patientId using operators like $eq, $gte, etc.
   */
  'filter.patientId'?: string;
  /**
   * Filter by guarantorId using operators like $eq, $gte, etc.
   */
  'filter.guarantorId'?: string;
  /**
   * Filter by status using operators like $eq, $gte, etc.
   */
  'filter.status'?: PaymentGuaranteeControllerReferredFilterStatus;
  /**
   * Filter by isPremium using operators like $eq, $gte, etc.
   */
  'filter.isPremium'?: PaymentGuaranteeControllerReferredFilterIsPremium;
  /**
   * Filter by invoiceId using operators like $eq, $gte, etc.
   */
  'filter.invoiceId'?: string;
  /**
   * Filter by invoice.number using operators like $eq, $gte, etc.
   */
  'filter.invoice.number'?: string;
  sortBy?: string[];
};
