/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type PaymentGuaranteeReportControllerPaymentGuaranteeReportSortType = typeof PaymentGuaranteeReportControllerPaymentGuaranteeReportSortType[keyof typeof PaymentGuaranteeReportControllerPaymentGuaranteeReportSortType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentGuaranteeReportControllerPaymentGuaranteeReportSortType = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
