/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type PaymentGateControllerFindAllParams = {
  /**
   * @maxLength 100
   */
  name?: string;
  /**
   * @maxLength 8
   */
  code?: string;
  page?: number;
  limit?: number;
};
