/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type PaymentGuaranteeControllerFindAllFilterStatus =
  (typeof PaymentGuaranteeControllerFindAllFilterStatus)[keyof typeof PaymentGuaranteeControllerFindAllFilterStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentGuaranteeControllerFindAllFilterStatus = {
  WAITING: 'WAITING',
  CONFIRMED: 'CONFIRMED',
  CANCELED: 'CANCELED',
} as const;
