/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { ReferralDiscountReportItemDtoDiscountMethod } from './referralDiscountReportItemDtoDiscountMethod';
import type { ReferralDiscountReportItemDtoStatus } from './referralDiscountReportItemDtoStatus';

export interface ReferralDiscountReportItemDto {
  id: string;
  date: string;
  patientName: string;
  patientDocNumber: string;
  nationalCode: string;
  guarantorName: string;
  discountMethod: ReferralDiscountReportItemDtoDiscountMethod;
  discountValue: number;
  /** @nullable */
  maxDiscountAmount: number | null;
  treatmentCategoryName: string;
  treatmentName: string;
  treatmentStepName: string;
  toothNumber: string;
  status: ReferralDiscountReportItemDtoStatus;
  invoiceNumber: string;
  appliedTo: string;
  isUsed: boolean;
  payablePrice: number;
}
