/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type ReferralDiscountReportControllerReferralDiscountReportStatus =
  (typeof ReferralDiscountReportControllerReferralDiscountReportStatus)[keyof typeof ReferralDiscountReportControllerReferralDiscountReportStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReferralDiscountReportControllerReferralDiscountReportStatus = {
  waiting: 'waiting',
  CONFIRMED_BY_PERSONNEL: 'CONFIRMED_BY_PERSONNEL',
  REJECTED_BY_PERSONNEL: 'REJECTED_BY_PERSONNEL',
  confirm: 'confirm',
  cancel: 'cancel',
} as const;
