/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { ReferralDiscountReportControllerReferralDiscountReportSortType } from './referralDiscountReportControllerReferralDiscountReportSortType';
import type { ReferralDiscountReportControllerReferralDiscountReportMethod } from './referralDiscountReportControllerReferralDiscountReportMethod';
import type { ReferralDiscountReportControllerReferralDiscountReportStatus } from './referralDiscountReportControllerReferralDiscountReportStatus';

export type ReferralDiscountReportControllerReferralDiscountReportParams = {
  sortType?: ReferralDiscountReportControllerReferralDiscountReportSortType;
  /**
   * If true, returns an Excel file instead of JSON grid data
   */
  exportGridData?: boolean;
  method?: ReferralDiscountReportControllerReferralDiscountReportMethod;
  status?: ReferralDiscountReportControllerReferralDiscountReportStatus;
  minMaxDiscountAmount?: number;
  maxMaxDiscountAmount?: number;
  isUsed?: boolean;
  patientId?: string;
  personnelId?: string;
  fromDate?: string;
  toDate?: string;
  page?: number;
  limit?: number;
};
