/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { ReferralDiscountReportControllerReferralDiscountExcelSortType } from './referralDiscountReportControllerReferralDiscountExcelSortType';
import type { ReferralDiscountReportControllerReferralDiscountExcelMethod } from './referralDiscountReportControllerReferralDiscountExcelMethod';
import type { ReferralDiscountReportControllerReferralDiscountExcelStatus } from './referralDiscountReportControllerReferralDiscountExcelStatus';

export type ReferralDiscountReportControllerReferralDiscountExcelParams = {
  sortType?: ReferralDiscountReportControllerReferralDiscountExcelSortType;
  method?: ReferralDiscountReportControllerReferralDiscountExcelMethod;
  status?: ReferralDiscountReportControllerReferralDiscountExcelStatus;
  minMaxDiscountAmount?: number;
  maxMaxDiscountAmount?: number;
  isUsed?: boolean;
  patientId?: string;
  personnelId?: string;
  fromDate?: string;
  toDate?: string;
};
