/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type RegisteredTreatmentPlanReportControllerRegisteredTreatmentPlansStatus =
  (typeof RegisteredTreatmentPlanReportControllerRegisteredTreatmentPlansStatus)[keyof typeof RegisteredTreatmentPlanReportControllerRegisteredTreatmentPlansStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisteredTreatmentPlanReportControllerRegisteredTreatmentPlansStatus = {
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_REVIEW: 'WAITING_FOR_REVIEW',
  SELECTED: 'SELECTED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
} as const;
