/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { PaginationMetaDto } from './paginationMetaDto';
import type { PaginationLinksDto } from './paginationLinksDto';
import type { RegisteredTreatmentPlanReportItemDto } from './registeredTreatmentPlanReportItemDto';

export interface RegisteredTreatmentPlanReportPaginatedResponse {
  meta: PaginationMetaDto;
  links: PaginationLinksDto;
  items: RegisteredTreatmentPlanReportItemDto[];
  /** Sum of amounts for current page */
  totalAmount: number;
}
