/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type ReviewRequestControllerFindAllStatus =
  (typeof ReviewRequestControllerFindAllStatus)[keyof typeof ReviewRequestControllerFindAllStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewRequestControllerFindAllStatus = {
  WATTING: 'WATTING',
  ASSIGNED: 'ASSIGNED',
  ANSWERED: 'ANSWERED',
  CLOSED: 'CLOSED',
} as const;
