/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type ReviewControllerFindReviewsOfMyAssignedReviewRequestCancelStage =
  (typeof ReviewControllerFindReviewsOfMyAssignedReviewRequestCancelStage)[keyof typeof ReviewControllerFindReviewsOfMyAssignedReviewRequestCancelStage];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewControllerFindReviewsOfMyAssignedReviewRequestCancelStage = {
  BEFORE_TREATMENT: 'BEFORE_TREATMENT',
  DURING_TREATMNET: 'DURING_TREATMNET',
} as const;
