/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { ReviewRequestsReportItemDtoStatus } from './reviewRequestsReportItemDtoStatus';

export interface ReviewRequestsReportItemDto {
  id: string;
  createdAt: string;
  patientName: string;
  patientDocNumber: string;
  nationalCode: string;
  treatmentCategoryName: string;
  treatmentName: string;
  treatmentStepName: string;
  status: ReviewRequestsReportItemDtoStatus;
  visitDoctorName: string;
  expertDoctorName: string;
  toothNumber: string;
}
