/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { ReviewRequestControllerSentReviewRequestsStatus } from './reviewRequestControllerSentReviewRequestsStatus';
import type { ReviewRequestControllerSentReviewRequestsSortType } from './reviewRequestControllerSentReviewRequestsSortType';
import type { ReviewRequestControllerSentReviewRequestsSortBy } from './reviewRequestControllerSentReviewRequestsSortBy';
import type { ReviewRequestControllerSentReviewRequestsCancelStage } from './reviewRequestControllerSentReviewRequestsCancelStage';
import type { ReviewRequestControllerSentReviewRequestsType } from './reviewRequestControllerSentReviewRequestsType';

export type ReviewRequestControllerSentReviewRequestsParams = {
  status?: ReviewRequestControllerSentReviewRequestsStatus;
  sortType?: ReviewRequestControllerSentReviewRequestsSortType;
  sortBy?: ReviewRequestControllerSentReviewRequestsSortBy;
  cancelStage?: ReviewRequestControllerSentReviewRequestsCancelStage;
  type?: ReviewRequestControllerSentReviewRequestsType;
  patientId?: string;
  page?: number;
  limit?: number;
};
