/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type ReviewRequestControllerRelatedReviewRequestsSortBy =
  (typeof ReviewRequestControllerRelatedReviewRequestsSortBy)[keyof typeof ReviewRequestControllerRelatedReviewRequestsSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewRequestControllerRelatedReviewRequestsSortBy = {
  createdAt: 'createdAt',
} as const;
