/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type ReviewControllerFindReviewsOfMyAssignedReviewRequestSortBy =
  (typeof ReviewControllerFindReviewsOfMyAssignedReviewRequestSortBy)[keyof typeof ReviewControllerFindReviewsOfMyAssignedReviewRequestSortBy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewControllerFindReviewsOfMyAssignedReviewRequestSortBy = {
  createdAt: 'createdAt',
} as const;
