/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type SpecialDiscountReportControllerSpecialDiscountExcelMethod = typeof SpecialDiscountReportControllerSpecialDiscountExcelMethod[keyof typeof SpecialDiscountReportControllerSpecialDiscountExcelMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpecialDiscountReportControllerSpecialDiscountExcelMethod = {
  FIXED: 'FIXED',
  PERCENTAGE: 'PERCENTAGE',
} as const;
