/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { TreatmentCategorySummaryReportControllerGetGridDataSortType } from './treatmentCategorySummaryReportControllerGetGridDataSortType';

export type TreatmentCategorySummaryReportControllerGetGridDataParams = {
  sortType?: TreatmentCategorySummaryReportControllerGetGridDataSortType;
  /**
   * If true, returns an Excel file instead of JSON grid data
   */
  exportGridData?: boolean;
  treatmentCategoryId?: string;
  fromDate?: string;
  toDate?: string;
  page?: number;
  limit?: number;
};
