/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { UpdateVacationDtoType } from './updateVacationDtoType';

export interface UpdateVacationDto {
  type: UpdateVacationDtoType;
  startDate: string;
  endDate: string;
  startTime: string;
  endTime: string;
  isUrgent?: boolean;
  days: number;
  description: string;
}
