/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { VacationControllerFindAllFilterIsUrgent } from './vacationControllerFindAllFilterIsUrgent';

export type VacationControllerFindAllParams = {
  page?: number;
  limit?: number;
  search?: string;
  /**
   * Filter by type using operators like $eq, $gte, etc.
   */
  'filter.type'?: string;
  /**
   * Filter by status using operators like $eq, $gte, etc.
   */
  'filter.status'?: string;
  /**
   * Filter by isRequestedByHR using operators like $eq, $gte, etc.
   */
  'filter.isRequestedByHR'?: string;
  /**
   * Filter by startDate using operators like $eq, $gte, etc.
   */
  'filter.startDate'?: string;
  /**
   * Filter by endDate using operators like $eq, $gte, etc.
   */
  'filter.endDate'?: string;
  /**
   * Filter by startTime using operators like $eq, $gte, etc.
   */
  'filter.startTime'?: string;
  /**
   * Filter by endTime using operators like $eq, $gte, etc.
   */
  'filter.endTime'?: string;
  /**
   * Filter by requestedBy.id using operators like $eq, $gte, etc.
   */
  'filter.requestedBy.id'?: string;
  /**
   * Filter by isUrgent using operators like $eq, $gte, etc.
   */
  'filter.isUrgent'?: VacationControllerFindAllFilterIsUrgent;
  sortBy?: string[];
};
