/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { VisitAppointmentControllerFindAllByPatientSortType } from './visitAppointmentControllerFindAllByPatientSortType';

export type VisitAppointmentControllerFindAllByPatientParams = {
  sortType?: VisitAppointmentControllerFindAllByPatientSortType;
  sortBy?: string;
  slotId?: string;
  name?: string;
  slotFromDate?: string;
  slotToDate?: string;
  slotStartTime?: string;
  slotEndTime?: string;
  page?: number;
  limit?: number;
};
