/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type WalletTransactionControllerFindAllByAdminType =
  (typeof WalletTransactionControllerFindAllByAdminType)[keyof typeof WalletTransactionControllerFindAllByAdminType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WalletTransactionControllerFindAllByAdminType = {
  deposit: 'deposit',
  withdrawal: 'withdrawal',
  transfer: 'transfer',
  loantransfer: 'loantransfer',
  loan: 'loan',
} as const;
