/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { WalletTransactionControllerFindAllByAdminSortType } from './walletTransactionControllerFindAllByAdminSortType';
import type { WalletTransactionControllerFindAllByAdminType } from './walletTransactionControllerFindAllByAdminType';
import type { WalletTransactionControllerFindAllByAdminStatus } from './walletTransactionControllerFindAllByAdminStatus';

export type WalletTransactionControllerFindAllByAdminParams = {
  sortType?: WalletTransactionControllerFindAllByAdminSortType;
  sortBy?: string;
  type?: WalletTransactionControllerFindAllByAdminType;
  createdAt?: string;
  status?: WalletTransactionControllerFindAllByAdminStatus;
  fromWalletId?: string;
  toWalletId?: string;
  walletId?: string;
  date?: string;
  page?: number;
  limit?: number;
};
