/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type WalletDecreaseReportControllerWalletDecreaseReportSortType =
  (typeof WalletDecreaseReportControllerWalletDecreaseReportSortType)[keyof typeof WalletDecreaseReportControllerWalletDecreaseReportSortType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WalletDecreaseReportControllerWalletDecreaseReportSortType = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
