/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { WalletControllerDetailsSortType } from './walletControllerDetailsSortType';
import type { WalletControllerDetailsType } from './walletControllerDetailsType';
import type { WalletControllerDetailsStatus } from './walletControllerDetailsStatus';

export type WalletControllerDetailsParams = {
  sortType?: WalletControllerDetailsSortType;
  sortBy?: string;
  type?: WalletControllerDetailsType;
  createdAt?: string;
  status?: WalletControllerDetailsStatus;
  fromWalletId?: string;
  toWalletId?: string;
  walletId?: string;
  date?: string;
  page?: number;
  limit?: number;
};
