/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import type { WalletTransactionControllerFindAllSortType } from './walletTransactionControllerFindAllSortType';
import type { WalletTransactionControllerFindAllType } from './walletTransactionControllerFindAllType';
import type { WalletTransactionControllerFindAllStatus } from './walletTransactionControllerFindAllStatus';

export type WalletTransactionControllerFindAllParams = {
  sortType?: WalletTransactionControllerFindAllSortType;
  sortBy?: string;
  type?: WalletTransactionControllerFindAllType;
  createdAt?: string;
  status?: WalletTransactionControllerFindAllStatus;
  fromWalletId?: string;
  toWalletId?: string;
  date?: string;
  page?: number;
  limit?: number;
};
