/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export interface WalletDecreaseReportItemDto {
  date: string;
  patientName: string;
  nationalCode: string;
  amount: number;
  userDescription: string;
  isCorrected: boolean;
  reductionReason: string;
}
