/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */

export type WorkScheduleControllerFindAllParams = {
  page?: number;
  limit?: number;
  search?: string;
  /**
   * Filter by dayOfWeek using operators like $eq, $gte, etc.
   */
  'filter.dayOfWeek'?: string;
  /**
   * Filter by personnelId using operators like $eq, $gte, etc.
   */
  'filter.personnelId'?: string;
  sortBy?: string[];
};
