/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { UpdateVisitAppointmentSettingDto, VisitAppointmentSettings } from '../../models2';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

export const visitAppointmentSettingsControllerFindAll = (signal?: AbortSignal) => {
  return apiInstance<VisitAppointmentSettings[]>({
    url: `/api/visit-appointment-settings`,
    method: 'GET',
    signal,
  });
};

export const getVisitAppointmentSettingsControllerFindAllQueryKey = () => {
  return [`/api/visit-appointment-settings`] as const;
};

export const getVisitAppointmentSettingsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
      TError,
      TData
    >
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getVisitAppointmentSettingsControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>
  > = ({ signal }) => visitAppointmentSettingsControllerFindAll(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VisitAppointmentSettingsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>
>;
export type VisitAppointmentSettingsControllerFindAllQueryError = unknown;

export function useVisitAppointmentSettingsControllerFindAll<
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVisitAppointmentSettingsControllerFindAll<
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVisitAppointmentSettingsControllerFindAll<
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useVisitAppointmentSettingsControllerFindAll<
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindAll>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVisitAppointmentSettingsControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const visitAppointmentSettingsControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<VisitAppointmentSettings>({
    url: `/api/visit-appointment-settings/${id}`,
    method: 'GET',
    signal,
  });
};

export const getVisitAppointmentSettingsControllerFindOneQueryKey = (id?: string) => {
  return [`/api/visit-appointment-settings/${id}`] as const;
};

export const getVisitAppointmentSettingsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getVisitAppointmentSettingsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>
  > = ({ signal }) => visitAppointmentSettingsControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type VisitAppointmentSettingsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>
>;
export type VisitAppointmentSettingsControllerFindOneQueryError = unknown;

export function useVisitAppointmentSettingsControllerFindOne<
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVisitAppointmentSettingsControllerFindOne<
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useVisitAppointmentSettingsControllerFindOne<
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useVisitAppointmentSettingsControllerFindOne<
  TData = Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof visitAppointmentSettingsControllerFindOne>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getVisitAppointmentSettingsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const visitAppointmentSettingsControllerUpdate = (
  id: string,
  updateVisitAppointmentSettingDto: UpdateVisitAppointmentSettingDto
) => {
  return apiInstance<VisitAppointmentSettings>({
    url: `/api/visit-appointment-settings/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateVisitAppointmentSettingDto,
  });
};

export const getVisitAppointmentSettingsControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof visitAppointmentSettingsControllerUpdate>>,
    TError,
    { id: string; data: UpdateVisitAppointmentSettingDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof visitAppointmentSettingsControllerUpdate>>,
  TError,
  { id: string; data: UpdateVisitAppointmentSettingDto },
  TContext
> => {
  const mutationKey = ['visitAppointmentSettingsControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof visitAppointmentSettingsControllerUpdate>>,
    { id: string; data: UpdateVisitAppointmentSettingDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return visitAppointmentSettingsControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type VisitAppointmentSettingsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof visitAppointmentSettingsControllerUpdate>>
>;
export type VisitAppointmentSettingsControllerUpdateMutationBody = UpdateVisitAppointmentSettingDto;
export type VisitAppointmentSettingsControllerUpdateMutationError = unknown;

export const useVisitAppointmentSettingsControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof visitAppointmentSettingsControllerUpdate>>,
      TError,
      { id: string; data: UpdateVisitAppointmentSettingDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof visitAppointmentSettingsControllerUpdate>>,
  TError,
  { id: string; data: UpdateVisitAppointmentSettingDto },
  TContext
> => {
  const mutationOptions = getVisitAppointmentSettingsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
