/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateDiscountDto,
  Discount,
  DiscountPaginatedResopnse,
  DiscountsControllerFindAllParams,
  DiscountsControllerUpdate200,
  GrantDiscountToPatientDto,
  UpdateDiscountDto,
} from '../../models1';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: create_discount
 */
export const discountsControllerCreate = (
  createDiscountDto: CreateDiscountDto,
  signal?: AbortSignal
) => {
  return apiInstance<Discount>({
    url: `/api/discounts`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createDiscountDto,
    signal,
  });
};

export const getDiscountsControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof discountsControllerCreate>>,
    TError,
    { data: CreateDiscountDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof discountsControllerCreate>>,
  TError,
  { data: CreateDiscountDto },
  TContext
> => {
  const mutationKey = ['discountsControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof discountsControllerCreate>>,
    { data: CreateDiscountDto }
  > = (props) => {
    const { data } = props ?? {};

    return discountsControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DiscountsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof discountsControllerCreate>>
>;
export type DiscountsControllerCreateMutationBody = CreateDiscountDto;
export type DiscountsControllerCreateMutationError = unknown;

/**
 * @summary required permisson: create_discount
 */
export const useDiscountsControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof discountsControllerCreate>>,
      TError,
      { data: CreateDiscountDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof discountsControllerCreate>>,
  TError,
  { data: CreateDiscountDto },
  TContext
> => {
  const mutationOptions = getDiscountsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_discount
 */
export const discountsControllerFindAll = (
  params?: DiscountsControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<void>({ url: `/api/discounts`, method: 'GET', params, signal });
};

export const getDiscountsControllerFindAllQueryKey = (
  params?: DiscountsControllerFindAllParams
) => {
  return [`/api/discounts`, ...(params ? [params] : [])] as const;
};

export const getDiscountsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof discountsControllerFindAll>>,
  TError = DiscountPaginatedResopnse,
>(
  params?: DiscountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDiscountsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof discountsControllerFindAll>>> = ({
    signal,
  }) => discountsControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof discountsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DiscountsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof discountsControllerFindAll>>
>;
export type DiscountsControllerFindAllQueryError = DiscountPaginatedResopnse;

export function useDiscountsControllerFindAll<
  TData = Awaited<ReturnType<typeof discountsControllerFindAll>>,
  TError = DiscountPaginatedResopnse,
>(
  params: undefined | DiscountsControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof discountsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof discountsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDiscountsControllerFindAll<
  TData = Awaited<ReturnType<typeof discountsControllerFindAll>>,
  TError = DiscountPaginatedResopnse,
>(
  params?: DiscountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof discountsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof discountsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDiscountsControllerFindAll<
  TData = Awaited<ReturnType<typeof discountsControllerFindAll>>,
  TError = DiscountPaginatedResopnse,
>(
  params?: DiscountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_discount
 */

export function useDiscountsControllerFindAll<
  TData = Awaited<ReturnType<typeof discountsControllerFindAll>>,
  TError = DiscountPaginatedResopnse,
>(
  params?: DiscountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDiscountsControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const discountsControllerFindByUser = (signal?: AbortSignal) => {
  return apiInstance<Discount[]>({ url: `/api/discounts/my-discounts`, method: 'GET', signal });
};

export const getDiscountsControllerFindByUserQueryKey = () => {
  return [`/api/discounts/my-discounts`] as const;
};

export const getDiscountsControllerFindByUserQueryOptions = <
  TData = Awaited<ReturnType<typeof discountsControllerFindByUser>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindByUser>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDiscountsControllerFindByUserQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof discountsControllerFindByUser>>> = ({
    signal,
  }) => discountsControllerFindByUser(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof discountsControllerFindByUser>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DiscountsControllerFindByUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof discountsControllerFindByUser>>
>;
export type DiscountsControllerFindByUserQueryError = unknown;

export function useDiscountsControllerFindByUser<
  TData = Awaited<ReturnType<typeof discountsControllerFindByUser>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindByUser>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof discountsControllerFindByUser>>,
          TError,
          Awaited<ReturnType<typeof discountsControllerFindByUser>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDiscountsControllerFindByUser<
  TData = Awaited<ReturnType<typeof discountsControllerFindByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindByUser>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof discountsControllerFindByUser>>,
          TError,
          Awaited<ReturnType<typeof discountsControllerFindByUser>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDiscountsControllerFindByUser<
  TData = Awaited<ReturnType<typeof discountsControllerFindByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindByUser>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDiscountsControllerFindByUser<
  TData = Awaited<ReturnType<typeof discountsControllerFindByUser>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindByUser>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDiscountsControllerFindByUserQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_discount
 */
export const discountsControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<Discount>({ url: `/api/discounts/${id}`, method: 'GET', signal });
};

export const getDiscountsControllerFindOneQueryKey = (id?: string) => {
  return [`/api/discounts/${id}`] as const;
};

export const getDiscountsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof discountsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDiscountsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof discountsControllerFindOne>>> = ({
    signal,
  }) => discountsControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof discountsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DiscountsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof discountsControllerFindOne>>
>;
export type DiscountsControllerFindOneQueryError = unknown;

export function useDiscountsControllerFindOne<
  TData = Awaited<ReturnType<typeof discountsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof discountsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof discountsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDiscountsControllerFindOne<
  TData = Awaited<ReturnType<typeof discountsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof discountsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof discountsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDiscountsControllerFindOne<
  TData = Awaited<ReturnType<typeof discountsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_discount
 */

export function useDiscountsControllerFindOne<
  TData = Awaited<ReturnType<typeof discountsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof discountsControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDiscountsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_discount
 */
export const discountsControllerUpdate = (id: string, updateDiscountDto: UpdateDiscountDto) => {
  return apiInstance<DiscountsControllerUpdate200>({
    url: `/api/discounts/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateDiscountDto,
  });
};

export const getDiscountsControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof discountsControllerUpdate>>,
    TError,
    { id: string; data: UpdateDiscountDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof discountsControllerUpdate>>,
  TError,
  { id: string; data: UpdateDiscountDto },
  TContext
> => {
  const mutationKey = ['discountsControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof discountsControllerUpdate>>,
    { id: string; data: UpdateDiscountDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return discountsControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DiscountsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof discountsControllerUpdate>>
>;
export type DiscountsControllerUpdateMutationBody = UpdateDiscountDto;
export type DiscountsControllerUpdateMutationError = unknown;

/**
 * @summary required permisson: update_discount
 */
export const useDiscountsControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof discountsControllerUpdate>>,
      TError,
      { id: string; data: UpdateDiscountDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof discountsControllerUpdate>>,
  TError,
  { id: string; data: UpdateDiscountDto },
  TContext
> => {
  const mutationOptions = getDiscountsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: delete_discount
 */
export const discountsControllerRemove = (id: string) => {
  return apiInstance<void>({ url: `/api/discounts/${id}`, method: 'DELETE' });
};

export const getDiscountsControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof discountsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof discountsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['discountsControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof discountsControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return discountsControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DiscountsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof discountsControllerRemove>>
>;

export type DiscountsControllerRemoveMutationError = unknown;

/**
 * @summary required permisson: delete_discount
 */
export const useDiscountsControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof discountsControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof discountsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDiscountsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const discountsControllerGetActivesByPatientId = (
  patientid: string,
  signal?: AbortSignal
) => {
  return apiInstance<Discount[]>({
    url: `/api/discounts/${patientid}/actives`,
    method: 'GET',
    signal,
  });
};

export const getDiscountsControllerGetActivesByPatientIdQueryKey = (patientid?: string) => {
  return [`/api/discounts/${patientid}/actives`] as const;
};

export const getDiscountsControllerGetActivesByPatientIdQueryOptions = <
  TData = Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
  TError = unknown,
>(
  patientid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getDiscountsControllerGetActivesByPatientIdQueryKey(patientid);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>
  > = ({ signal }) => discountsControllerGetActivesByPatientId(patientid, signal);

  return { queryKey, queryFn, enabled: !!patientid, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DiscountsControllerGetActivesByPatientIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>
>;
export type DiscountsControllerGetActivesByPatientIdQueryError = unknown;

export function useDiscountsControllerGetActivesByPatientId<
  TData = Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
  TError = unknown,
>(
  patientid: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
          TError,
          Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDiscountsControllerGetActivesByPatientId<
  TData = Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
  TError = unknown,
>(
  patientid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
          TError,
          Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDiscountsControllerGetActivesByPatientId<
  TData = Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
  TError = unknown,
>(
  patientid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDiscountsControllerGetActivesByPatientId<
  TData = Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
  TError = unknown,
>(
  patientid: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof discountsControllerGetActivesByPatientId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDiscountsControllerGetActivesByPatientIdQueryOptions(patientid, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_discount
 */
export const discountsControllerGrantToPatient = (
  grantDiscountToPatientDto: GrantDiscountToPatientDto,
  signal?: AbortSignal
) => {
  return apiInstance<void>({
    url: `/api/discounts/grant-to-patient`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: grantDiscountToPatientDto,
    signal,
  });
};

export const getDiscountsControllerGrantToPatientMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof discountsControllerGrantToPatient>>,
    TError,
    { data: GrantDiscountToPatientDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof discountsControllerGrantToPatient>>,
  TError,
  { data: GrantDiscountToPatientDto },
  TContext
> => {
  const mutationKey = ['discountsControllerGrantToPatient'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof discountsControllerGrantToPatient>>,
    { data: GrantDiscountToPatientDto }
  > = (props) => {
    const { data } = props ?? {};

    return discountsControllerGrantToPatient(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DiscountsControllerGrantToPatientMutationResult = NonNullable<
  Awaited<ReturnType<typeof discountsControllerGrantToPatient>>
>;
export type DiscountsControllerGrantToPatientMutationBody = GrantDiscountToPatientDto;
export type DiscountsControllerGrantToPatientMutationError = unknown;

/**
 * @summary required permisson: update_discount
 */
export const useDiscountsControllerGrantToPatient = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof discountsControllerGrantToPatient>>,
      TError,
      { data: GrantDiscountToPatientDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof discountsControllerGrantToPatient>>,
  TError,
  { data: GrantDiscountToPatientDto },
  TContext
> => {
  const mutationOptions = getDiscountsControllerGrantToPatientMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
