/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  File,
  PaginatedFindAllUsersByRolenameResponse,
  Permission,
  RegisterDto,
  Role,
  SaveFingerprintDto,
  UpdateProfileDto,
  UpdateUserDto,
  User,
  UserControllerFindAll200,
  UserControllerFindAllByRolenameParams,
  UserControllerFindAllParams,
  UserControllerUpdate200,
  UserControllerUpdateProfile200,
  UserPaginatedResopnse,
  VerifyUserDto,
} from '../../models';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

export const userControllerFindAll = (
  params?: UserControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<UserControllerFindAll200>({
    url: `/api/users`,
    method: 'GET',
    params,
    signal,
  });
};

export const getUserControllerFindAllQueryKey = (params?: UserControllerFindAllParams) => {
  return [`/api/users`, ...(params ? [params] : [])] as const;
};

export const getUserControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerFindAll>>,
  TError = UserPaginatedResopnse,
>(
  params?: UserControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerFindAll>>> = ({ signal }) =>
    userControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindAll>>
>;
export type UserControllerFindAllQueryError = UserPaginatedResopnse;

export function useUserControllerFindAll<
  TData = Awaited<ReturnType<typeof userControllerFindAll>>,
  TError = UserPaginatedResopnse,
>(
  params: undefined | UserControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof userControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerFindAll<
  TData = Awaited<ReturnType<typeof userControllerFindAll>>,
  TError = UserPaginatedResopnse,
>(
  params?: UserControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof userControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerFindAll<
  TData = Awaited<ReturnType<typeof userControllerFindAll>>,
  TError = UserPaginatedResopnse,
>(
  params?: UserControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerFindAll<
  TData = Awaited<ReturnType<typeof userControllerFindAll>>,
  TError = UserPaginatedResopnse,
>(
  params?: UserControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const userControllerCreate = (registerDto: RegisterDto, signal?: AbortSignal) => {
  return apiInstance<User>({
    url: `/api/users`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: registerDto,
    signal,
  });
};

export const getUserControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerCreate>>,
    TError,
    { data: RegisterDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerCreate>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  const mutationKey = ['userControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerCreate>>,
    { data: RegisterDto }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerCreate>>
>;
export type UserControllerCreateMutationBody = RegisterDto;
export type UserControllerCreateMutationError = unknown;

export const useUserControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerCreate>>,
      TError,
      { data: RegisterDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerCreate>>,
  TError,
  { data: RegisterDto },
  TContext
> => {
  const mutationOptions = getUserControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const userControllerFindAllByRolename = (
  params?: UserControllerFindAllByRolenameParams,
  signal?: AbortSignal
) => {
  return apiInstance<PaginatedFindAllUsersByRolenameResponse>({
    url: `/api/users/find-all-by-rolename`,
    method: 'GET',
    params,
    signal,
  });
};

export const getUserControllerFindAllByRolenameQueryKey = (
  params?: UserControllerFindAllByRolenameParams
) => {
  return [`/api/users/find-all-by-rolename`, ...(params ? [params] : [])] as const;
};

export const getUserControllerFindAllByRolenameQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerFindAllByRolename>>,
  TError = unknown,
>(
  params?: UserControllerFindAllByRolenameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAllByRolename>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerFindAllByRolenameQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerFindAllByRolename>>> = ({
    signal,
  }) => userControllerFindAllByRolename(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerFindAllByRolename>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerFindAllByRolenameQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindAllByRolename>>
>;
export type UserControllerFindAllByRolenameQueryError = unknown;

export function useUserControllerFindAllByRolename<
  TData = Awaited<ReturnType<typeof userControllerFindAllByRolename>>,
  TError = unknown,
>(
  params: undefined | UserControllerFindAllByRolenameParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAllByRolename>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerFindAllByRolename>>,
          TError,
          Awaited<ReturnType<typeof userControllerFindAllByRolename>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerFindAllByRolename<
  TData = Awaited<ReturnType<typeof userControllerFindAllByRolename>>,
  TError = unknown,
>(
  params?: UserControllerFindAllByRolenameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAllByRolename>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerFindAllByRolename>>,
          TError,
          Awaited<ReturnType<typeof userControllerFindAllByRolename>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerFindAllByRolename<
  TData = Awaited<ReturnType<typeof userControllerFindAllByRolename>>,
  TError = unknown,
>(
  params?: UserControllerFindAllByRolenameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAllByRolename>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerFindAllByRolename<
  TData = Awaited<ReturnType<typeof userControllerFindAllByRolename>>,
  TError = unknown,
>(
  params?: UserControllerFindAllByRolenameParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindAllByRolename>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerFindAllByRolenameQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const userControllerGetProfile = (signal?: AbortSignal) => {
  return apiInstance<User>({ url: `/api/users/profile`, method: 'GET', signal });
};

export const getUserControllerGetProfileQueryKey = () => {
  return [`/api/users/profile`] as const;
};

export const getUserControllerGetProfileQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerGetProfileQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetProfile>>> = ({
    signal,
  }) => userControllerGetProfile(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetProfile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetProfileQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetProfile>>
>;
export type UserControllerGetProfileQueryError = unknown;

export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetProfile>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetProfile>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerGetProfile<
  TData = Awaited<ReturnType<typeof userControllerGetProfile>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetProfile>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerGetProfileQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const userControllerUpdateProfile = (updateProfileDto: UpdateProfileDto) => {
  return apiInstance<UserControllerUpdateProfile200>({
    url: `/api/users/profile`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateProfileDto,
  });
};

export const getUserControllerUpdateProfileMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpdateProfile>>,
    TError,
    { data: UpdateProfileDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUpdateProfile>>,
  TError,
  { data: UpdateProfileDto },
  TContext
> => {
  const mutationKey = ['userControllerUpdateProfile'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUpdateProfile>>,
    { data: UpdateProfileDto }
  > = (props) => {
    const { data } = props ?? {};

    return userControllerUpdateProfile(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateProfileMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdateProfile>>
>;
export type UserControllerUpdateProfileMutationBody = UpdateProfileDto;
export type UserControllerUpdateProfileMutationError = unknown;

export const useUserControllerUpdateProfile = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUpdateProfile>>,
      TError,
      { data: UpdateProfileDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUpdateProfile>>,
  TError,
  { data: UpdateProfileDto },
  TContext
> => {
  const mutationOptions = getUserControllerUpdateProfileMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const userControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<User>({ url: `/api/users/${id}`, method: 'GET', signal });
};

export const getUserControllerFindOneQueryKey = (id?: string) => {
  return [`/api/users/${id}`] as const;
};

export const getUserControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerFindOne>>> = ({ signal }) =>
    userControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerFindOne>>
>;
export type UserControllerFindOneQueryError = unknown;

export function useUserControllerFindOne<
  TData = Awaited<ReturnType<typeof userControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof userControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerFindOne<
  TData = Awaited<ReturnType<typeof userControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof userControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerFindOne<
  TData = Awaited<ReturnType<typeof userControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerFindOne<
  TData = Awaited<ReturnType<typeof userControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const userControllerUpdate = (id: string, updateUserDto: UpdateUserDto) => {
  return apiInstance<UserControllerUpdate200>({
    url: `/api/users/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateUserDto,
  });
};

export const getUserControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpdate>>,
    TError,
    { id: string; data: UpdateUserDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUpdate>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  const mutationKey = ['userControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUpdate>>,
    { id: string; data: UpdateUserDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return userControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpdate>>
>;
export type UserControllerUpdateMutationBody = UpdateUserDto;
export type UserControllerUpdateMutationError = unknown;

export const useUserControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUpdate>>,
      TError,
      { id: string; data: UpdateUserDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUpdate>>,
  TError,
  { id: string; data: UpdateUserDto },
  TContext
> => {
  const mutationOptions = getUserControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const userControllerDelete = (id: string) => {
  return apiInstance<void>({ url: `/api/users/${id}`, method: 'DELETE' });
};

export const getUserControllerDeleteMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['userControllerDelete'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return userControllerDelete(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerDelete>>
>;

export type UserControllerDeleteMutationError = unknown;

export const useUserControllerDelete = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getUserControllerDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const userControllerRestore = (id: string) => {
  return apiInstance<void>({ url: `/api/users/${id}`, method: 'PATCH' });
};

export const getUserControllerRestoreMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerRestore>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerRestore>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['userControllerRestore'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerRestore>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return userControllerRestore(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerRestoreMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerRestore>>
>;

export type UserControllerRestoreMutationError = unknown;

export const useUserControllerRestore = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerRestore>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerRestore>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getUserControllerRestoreMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const userControllerGetPermissions = (signal?: AbortSignal) => {
  return apiInstance<Permission[]>({
    url: `/api/users/profile/permissions`,
    method: 'GET',
    signal,
  });
};

export const getUserControllerGetPermissionsQueryKey = () => {
  return [`/api/users/profile/permissions`] as const;
};

export const getUserControllerGetPermissionsQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetPermissions>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof userControllerGetPermissions>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerGetPermissionsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetPermissions>>> = ({
    signal,
  }) => userControllerGetPermissions(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetPermissions>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetPermissionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetPermissions>>
>;
export type UserControllerGetPermissionsQueryError = unknown;

export function useUserControllerGetPermissions<
  TData = Awaited<ReturnType<typeof userControllerGetPermissions>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetPermissions>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetPermissions>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetPermissions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetPermissions<
  TData = Awaited<ReturnType<typeof userControllerGetPermissions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetPermissions>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetPermissions>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetPermissions>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetPermissions<
  TData = Awaited<ReturnType<typeof userControllerGetPermissions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetPermissions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerGetPermissions<
  TData = Awaited<ReturnType<typeof userControllerGetPermissions>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetPermissions>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerGetPermissionsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const userControllerGetRoles = (signal?: AbortSignal) => {
  return apiInstance<Role[]>({ url: `/api/users/profile/roles`, method: 'GET', signal });
};

export const getUserControllerGetRolesQueryKey = () => {
  return [`/api/users/profile/roles`] as const;
};

export const getUserControllerGetRolesQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetRoles>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<Awaited<ReturnType<typeof userControllerGetRoles>>, TError, TData>
  >;
}) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerGetRolesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetRoles>>> = ({ signal }) =>
    userControllerGetRoles(signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetRoles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetRolesQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetRoles>>
>;
export type UserControllerGetRolesQueryError = unknown;

export function useUserControllerGetRoles<
  TData = Awaited<ReturnType<typeof userControllerGetRoles>>,
  TError = unknown,
>(
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetRoles>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetRoles>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetRoles>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetRoles<
  TData = Awaited<ReturnType<typeof userControllerGetRoles>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetRoles>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetRoles>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetRoles>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetRoles<
  TData = Awaited<ReturnType<typeof userControllerGetRoles>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetRoles>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerGetRoles<
  TData = Awaited<ReturnType<typeof userControllerGetRoles>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetRoles>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerGetRolesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const userControllerUpload = (id: string, signal?: AbortSignal) => {
  return apiInstance<void>({ url: `/api/users/${id}/files`, method: 'POST', signal });
};

export const getUserControllerUploadMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerUpload>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerUpload>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['userControllerUpload'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerUpload>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return userControllerUpload(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerUploadMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerUpload>>
>;

export type UserControllerUploadMutationError = unknown;

export const useUserControllerUpload = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerUpload>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerUpload>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getUserControllerUploadMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const userControllerGetFiles = (id: string, signal?: AbortSignal) => {
  return apiInstance<File[]>({ url: `/api/users/${id}/files`, method: 'GET', signal });
};

export const getUserControllerGetFilesQueryKey = (id?: string) => {
  return [`/api/users/${id}/files`] as const;
};

export const getUserControllerGetFilesQueryOptions = <
  TData = Awaited<ReturnType<typeof userControllerGetFiles>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetFiles>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUserControllerGetFilesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetFiles>>> = ({ signal }) =>
    userControllerGetFiles(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof userControllerGetFiles>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UserControllerGetFilesQueryResult = NonNullable<
  Awaited<ReturnType<typeof userControllerGetFiles>>
>;
export type UserControllerGetFilesQueryError = unknown;

export function useUserControllerGetFiles<
  TData = Awaited<ReturnType<typeof userControllerGetFiles>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetFiles>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetFiles>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetFiles>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetFiles<
  TData = Awaited<ReturnType<typeof userControllerGetFiles>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetFiles>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userControllerGetFiles>>,
          TError,
          Awaited<ReturnType<typeof userControllerGetFiles>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useUserControllerGetFiles<
  TData = Awaited<ReturnType<typeof userControllerGetFiles>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetFiles>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useUserControllerGetFiles<
  TData = Awaited<ReturnType<typeof userControllerGetFiles>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof userControllerGetFiles>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getUserControllerGetFilesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const userControllerVerify = (id: string, verifyUserDto: VerifyUserDto) => {
  return apiInstance<void>({
    url: `/api/users/${id}/verify`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: verifyUserDto,
  });
};

export const getUserControllerVerifyMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerVerify>>,
    TError,
    { id: string; data: VerifyUserDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerVerify>>,
  TError,
  { id: string; data: VerifyUserDto },
  TContext
> => {
  const mutationKey = ['userControllerVerify'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerVerify>>,
    { id: string; data: VerifyUserDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return userControllerVerify(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerVerifyMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerVerify>>
>;
export type UserControllerVerifyMutationBody = VerifyUserDto;
export type UserControllerVerifyMutationError = unknown;

export const useUserControllerVerify = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerVerify>>,
      TError,
      { id: string; data: VerifyUserDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerVerify>>,
  TError,
  { id: string; data: VerifyUserDto },
  TContext
> => {
  const mutationOptions = getUserControllerVerifyMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const userControllerSaveFingerprint = (
  userId: string,
  saveFingerprintDto: SaveFingerprintDto
) => {
  return apiInstance<void>({
    url: `/api/users/fingerprint/${userId}`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: saveFingerprintDto,
  });
};

export const getUserControllerSaveFingerprintMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof userControllerSaveFingerprint>>,
    TError,
    { userId: string; data: SaveFingerprintDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof userControllerSaveFingerprint>>,
  TError,
  { userId: string; data: SaveFingerprintDto },
  TContext
> => {
  const mutationKey = ['userControllerSaveFingerprint'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof userControllerSaveFingerprint>>,
    { userId: string; data: SaveFingerprintDto }
  > = (props) => {
    const { userId, data } = props ?? {};

    return userControllerSaveFingerprint(userId, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type UserControllerSaveFingerprintMutationResult = NonNullable<
  Awaited<ReturnType<typeof userControllerSaveFingerprint>>
>;
export type UserControllerSaveFingerprintMutationBody = SaveFingerprintDto;
export type UserControllerSaveFingerprintMutationError = unknown;

export const useUserControllerSaveFingerprint = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof userControllerSaveFingerprint>>,
      TError,
      { userId: string; data: SaveFingerprintDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof userControllerSaveFingerprint>>,
  TError,
  { userId: string; data: SaveFingerprintDto },
  TContext
> => {
  const mutationOptions = getUserControllerSaveFingerprintMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
