/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AddTreatmentPlanDto,
  AttachPaymentGuaranteeDto,
  AttachRefferalDiscount,
  CreateInvoiceDto,
  DeleteTreatmentPlanDto,
  Invoice,
  InvoiceControllerAddTreatmentPlan200,
  InvoiceControllerDeleteTreatmentPlan200,
  InvoiceControllerFindAllParams,
  InvoiceControllerFindMineParams,
  InvoiceControllerFindOneMineParams,
  InvoiceControllerFindOneParams,
  InvoiceControllerRecalculate200,
  InvoicePaginatedResopnse,
  UpdateInvoiceDto,
} from '../../models2';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: create_invoice
 */
export const invoiceControllerCreate = (
  createInvoiceDto: CreateInvoiceDto,
  signal?: AbortSignal
) => {
  return apiInstance<Invoice>({
    url: `/api/invoices`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createInvoiceDto,
    signal,
  });
};

export const getInvoiceControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceControllerCreate>>,
    TError,
    { data: CreateInvoiceDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceControllerCreate>>,
  TError,
  { data: CreateInvoiceDto },
  TContext
> => {
  const mutationKey = ['invoiceControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceControllerCreate>>,
    { data: CreateInvoiceDto }
  > = (props) => {
    const { data } = props ?? {};

    return invoiceControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerCreate>>
>;
export type InvoiceControllerCreateMutationBody = CreateInvoiceDto;
export type InvoiceControllerCreateMutationError = unknown;

/**
 * @summary required permisson: create_invoice
 */
export const useInvoiceControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceControllerCreate>>,
      TError,
      { data: CreateInvoiceDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceControllerCreate>>,
  TError,
  { data: CreateInvoiceDto },
  TContext
> => {
  const mutationOptions = getInvoiceControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_invoice
 */
export const invoiceControllerFindAll = (
  params?: InvoiceControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<void>({ url: `/api/invoices`, method: 'GET', params, signal });
};

export const getInvoiceControllerFindAllQueryKey = (params?: InvoiceControllerFindAllParams) => {
  return [`/api/invoices`, ...(params ? [params] : [])] as const;
};

export const getInvoiceControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerFindAll>>,
  TError = InvoicePaginatedResopnse,
>(
  params?: InvoiceControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceControllerFindAll>>> = ({
    signal,
  }) => invoiceControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerFindAll>>
>;
export type InvoiceControllerFindAllQueryError = InvoicePaginatedResopnse;

export function useInvoiceControllerFindAll<
  TData = Awaited<ReturnType<typeof invoiceControllerFindAll>>,
  TError = InvoicePaginatedResopnse,
>(
  params: undefined | InvoiceControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindAll<
  TData = Awaited<ReturnType<typeof invoiceControllerFindAll>>,
  TError = InvoicePaginatedResopnse,
>(
  params?: InvoiceControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindAll<
  TData = Awaited<ReturnType<typeof invoiceControllerFindAll>>,
  TError = InvoicePaginatedResopnse,
>(
  params?: InvoiceControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_invoice
 */

export function useInvoiceControllerFindAll<
  TData = Awaited<ReturnType<typeof invoiceControllerFindAll>>,
  TError = InvoicePaginatedResopnse,
>(
  params?: InvoiceControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const invoiceControllerFindMine = (
  params?: InvoiceControllerFindMineParams,
  signal?: AbortSignal
) => {
  return apiInstance<void>({ url: `/api/invoices/mine`, method: 'GET', params, signal });
};

export const getInvoiceControllerFindMineQueryKey = (params?: InvoiceControllerFindMineParams) => {
  return [`/api/invoices/mine`, ...(params ? [params] : [])] as const;
};

export const getInvoiceControllerFindMineQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerFindMine>>,
  TError = InvoicePaginatedResopnse,
>(
  params?: InvoiceControllerFindMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindMine>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerFindMineQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceControllerFindMine>>> = ({
    signal,
  }) => invoiceControllerFindMine(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerFindMine>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerFindMineQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerFindMine>>
>;
export type InvoiceControllerFindMineQueryError = InvoicePaginatedResopnse;

export function useInvoiceControllerFindMine<
  TData = Awaited<ReturnType<typeof invoiceControllerFindMine>>,
  TError = InvoicePaginatedResopnse,
>(
  params: undefined | InvoiceControllerFindMineParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindMine>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindMine>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindMine<
  TData = Awaited<ReturnType<typeof invoiceControllerFindMine>>,
  TError = InvoicePaginatedResopnse,
>(
  params?: InvoiceControllerFindMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindMine>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindMine>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindMine>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindMine<
  TData = Awaited<ReturnType<typeof invoiceControllerFindMine>>,
  TError = InvoicePaginatedResopnse,
>(
  params?: InvoiceControllerFindMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInvoiceControllerFindMine<
  TData = Awaited<ReturnType<typeof invoiceControllerFindMine>>,
  TError = InvoicePaginatedResopnse,
>(
  params?: InvoiceControllerFindMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerFindMineQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const invoiceControllerFindOneMine = (
  id: string,
  params?: InvoiceControllerFindOneMineParams,
  signal?: AbortSignal
) => {
  return apiInstance<Invoice>({ url: `/api/invoices/mine/${id}`, method: 'GET', params, signal });
};

export const getInvoiceControllerFindOneMineQueryKey = (
  id?: string,
  params?: InvoiceControllerFindOneMineParams
) => {
  return [`/api/invoices/mine/${id}`, ...(params ? [params] : [])] as const;
};

export const getInvoiceControllerFindOneMineQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerFindOneMine>>,
  TError = unknown,
>(
  id: string,
  params?: InvoiceControllerFindOneMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOneMine>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerFindOneMineQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceControllerFindOneMine>>> = ({
    signal,
  }) => invoiceControllerFindOneMine(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerFindOneMine>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerFindOneMineQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerFindOneMine>>
>;
export type InvoiceControllerFindOneMineQueryError = unknown;

export function useInvoiceControllerFindOneMine<
  TData = Awaited<ReturnType<typeof invoiceControllerFindOneMine>>,
  TError = unknown,
>(
  id: string,
  params: undefined | InvoiceControllerFindOneMineParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOneMine>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindOneMine>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindOneMine>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindOneMine<
  TData = Awaited<ReturnType<typeof invoiceControllerFindOneMine>>,
  TError = unknown,
>(
  id: string,
  params?: InvoiceControllerFindOneMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOneMine>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindOneMine>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindOneMine>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindOneMine<
  TData = Awaited<ReturnType<typeof invoiceControllerFindOneMine>>,
  TError = unknown,
>(
  id: string,
  params?: InvoiceControllerFindOneMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOneMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInvoiceControllerFindOneMine<
  TData = Awaited<ReturnType<typeof invoiceControllerFindOneMine>>,
  TError = unknown,
>(
  id: string,
  params?: InvoiceControllerFindOneMineParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOneMine>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerFindOneMineQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_invoice
 */
export const invoiceControllerFindOne = (
  id: string,
  params?: InvoiceControllerFindOneParams,
  signal?: AbortSignal
) => {
  return apiInstance<Invoice>({ url: `/api/invoices/${id}`, method: 'GET', params, signal });
};

export const getInvoiceControllerFindOneQueryKey = (
  id?: string,
  params?: InvoiceControllerFindOneParams
) => {
  return [`/api/invoices/${id}`, ...(params ? [params] : [])] as const;
};

export const getInvoiceControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: InvoiceControllerFindOneParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerFindOneQueryKey(id, params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceControllerFindOne>>> = ({
    signal,
  }) => invoiceControllerFindOne(id, params, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerFindOne>>
>;
export type InvoiceControllerFindOneQueryError = unknown;

export function useInvoiceControllerFindOne<
  TData = Awaited<ReturnType<typeof invoiceControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params: undefined | InvoiceControllerFindOneParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindOne<
  TData = Awaited<ReturnType<typeof invoiceControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: InvoiceControllerFindOneParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindOne<
  TData = Awaited<ReturnType<typeof invoiceControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: InvoiceControllerFindOneParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_invoice
 */

export function useInvoiceControllerFindOne<
  TData = Awaited<ReturnType<typeof invoiceControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  params?: InvoiceControllerFindOneParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerFindOneQueryOptions(id, params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_invoice
 */
export const invoiceControllerUpdate = (id: string, updateInvoiceDto: UpdateInvoiceDto) => {
  return apiInstance<Invoice>({
    url: `/api/invoices/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateInvoiceDto,
  });
};

export const getInvoiceControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceControllerUpdate>>,
    TError,
    { id: string; data: UpdateInvoiceDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceControllerUpdate>>,
  TError,
  { id: string; data: UpdateInvoiceDto },
  TContext
> => {
  const mutationKey = ['invoiceControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceControllerUpdate>>,
    { id: string; data: UpdateInvoiceDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return invoiceControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerUpdate>>
>;
export type InvoiceControllerUpdateMutationBody = UpdateInvoiceDto;
export type InvoiceControllerUpdateMutationError = unknown;

/**
 * @summary required permisson: update_invoice
 */
export const useInvoiceControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceControllerUpdate>>,
      TError,
      { id: string; data: UpdateInvoiceDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceControllerUpdate>>,
  TError,
  { id: string; data: UpdateInvoiceDto },
  TContext
> => {
  const mutationOptions = getInvoiceControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_invoice
 */
export const invoiceControllerFindByTreatmentPlanId = (id: string, signal?: AbortSignal) => {
  return apiInstance<Invoice[]>({
    url: `/api/invoices/treatment-plan/${id}`,
    method: 'GET',
    signal,
  });
};

export const getInvoiceControllerFindByTreatmentPlanIdQueryKey = (id?: string) => {
  return [`/api/invoices/treatment-plan/${id}`] as const;
};

export const getInvoiceControllerFindByTreatmentPlanIdQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
        TError,
        TData
      >
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerFindByTreatmentPlanIdQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>
  > = ({ signal }) => invoiceControllerFindByTreatmentPlanId(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerFindByTreatmentPlanIdQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>
>;
export type InvoiceControllerFindByTreatmentPlanIdQueryError = unknown;

export function useInvoiceControllerFindByTreatmentPlanId<
  TData = Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindByTreatmentPlanId<
  TData = Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerFindByTreatmentPlanId<
  TData = Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_invoice
 */

export function useInvoiceControllerFindByTreatmentPlanId<
  TData = Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof invoiceControllerFindByTreatmentPlanId>>,
        TError,
        TData
      >
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerFindByTreatmentPlanIdQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_invoice
 */
export const invoiceControllerAttachReferralDiscount = (
  id: string,
  attachRefferalDiscount: AttachRefferalDiscount
) => {
  return apiInstance<Invoice>({
    url: `/api/invoices/${id}/atach-referral-discount`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: attachRefferalDiscount,
  });
};

export const getInvoiceControllerAttachReferralDiscountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceControllerAttachReferralDiscount>>,
    TError,
    { id: string; data: AttachRefferalDiscount },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceControllerAttachReferralDiscount>>,
  TError,
  { id: string; data: AttachRefferalDiscount },
  TContext
> => {
  const mutationKey = ['invoiceControllerAttachReferralDiscount'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceControllerAttachReferralDiscount>>,
    { id: string; data: AttachRefferalDiscount }
  > = (props) => {
    const { id, data } = props ?? {};

    return invoiceControllerAttachReferralDiscount(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceControllerAttachReferralDiscountMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerAttachReferralDiscount>>
>;
export type InvoiceControllerAttachReferralDiscountMutationBody = AttachRefferalDiscount;
export type InvoiceControllerAttachReferralDiscountMutationError = unknown;

/**
 * @summary required permisson: update_invoice
 */
export const useInvoiceControllerAttachReferralDiscount = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceControllerAttachReferralDiscount>>,
      TError,
      { id: string; data: AttachRefferalDiscount },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceControllerAttachReferralDiscount>>,
  TError,
  { id: string; data: AttachRefferalDiscount },
  TContext
> => {
  const mutationOptions = getInvoiceControllerAttachReferralDiscountMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_invoice
 */
export const invoiceControllerAtachPayemntGuarantee = (
  id: string,
  attachPaymentGuaranteeDto: AttachPaymentGuaranteeDto
) => {
  return apiInstance<Invoice>({
    url: `/api/invoices/${id}/atach-payment-guarantee`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: attachPaymentGuaranteeDto,
  });
};

export const getInvoiceControllerAtachPayemntGuaranteeMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceControllerAtachPayemntGuarantee>>,
    TError,
    { id: string; data: AttachPaymentGuaranteeDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceControllerAtachPayemntGuarantee>>,
  TError,
  { id: string; data: AttachPaymentGuaranteeDto },
  TContext
> => {
  const mutationKey = ['invoiceControllerAtachPayemntGuarantee'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceControllerAtachPayemntGuarantee>>,
    { id: string; data: AttachPaymentGuaranteeDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return invoiceControllerAtachPayemntGuarantee(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceControllerAtachPayemntGuaranteeMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerAtachPayemntGuarantee>>
>;
export type InvoiceControllerAtachPayemntGuaranteeMutationBody = AttachPaymentGuaranteeDto;
export type InvoiceControllerAtachPayemntGuaranteeMutationError = unknown;

/**
 * @summary required permisson: update_invoice
 */
export const useInvoiceControllerAtachPayemntGuarantee = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceControllerAtachPayemntGuarantee>>,
      TError,
      { id: string; data: AttachPaymentGuaranteeDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceControllerAtachPayemntGuarantee>>,
  TError,
  { id: string; data: AttachPaymentGuaranteeDto },
  TContext
> => {
  const mutationOptions = getInvoiceControllerAtachPayemntGuaranteeMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_invoice
 */
export const invoiceControllerAddTreatmentPlan = (
  id: string,
  addTreatmentPlanDto: AddTreatmentPlanDto
) => {
  return apiInstance<InvoiceControllerAddTreatmentPlan200>({
    url: `/api/invoices/${id}/add-treatment-plan`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: addTreatmentPlanDto,
  });
};

export const getInvoiceControllerAddTreatmentPlanMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceControllerAddTreatmentPlan>>,
    TError,
    { id: string; data: AddTreatmentPlanDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceControllerAddTreatmentPlan>>,
  TError,
  { id: string; data: AddTreatmentPlanDto },
  TContext
> => {
  const mutationKey = ['invoiceControllerAddTreatmentPlan'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceControllerAddTreatmentPlan>>,
    { id: string; data: AddTreatmentPlanDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return invoiceControllerAddTreatmentPlan(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceControllerAddTreatmentPlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerAddTreatmentPlan>>
>;
export type InvoiceControllerAddTreatmentPlanMutationBody = AddTreatmentPlanDto;
export type InvoiceControllerAddTreatmentPlanMutationError = unknown;

/**
 * @summary required permisson: update_invoice
 */
export const useInvoiceControllerAddTreatmentPlan = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceControllerAddTreatmentPlan>>,
      TError,
      { id: string; data: AddTreatmentPlanDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceControllerAddTreatmentPlan>>,
  TError,
  { id: string; data: AddTreatmentPlanDto },
  TContext
> => {
  const mutationOptions = getInvoiceControllerAddTreatmentPlanMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: delete_invoice
 */
export const invoiceControllerDeleteTreatmentPlan = (
  id: string,
  deleteTreatmentPlanDto: DeleteTreatmentPlanDto
) => {
  return apiInstance<InvoiceControllerDeleteTreatmentPlan200>({
    url: `/api/invoices/${id}/delete-treatment-plan`,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    data: deleteTreatmentPlanDto,
  });
};

export const getInvoiceControllerDeleteTreatmentPlanMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceControllerDeleteTreatmentPlan>>,
    TError,
    { id: string; data: DeleteTreatmentPlanDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceControllerDeleteTreatmentPlan>>,
  TError,
  { id: string; data: DeleteTreatmentPlanDto },
  TContext
> => {
  const mutationKey = ['invoiceControllerDeleteTreatmentPlan'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceControllerDeleteTreatmentPlan>>,
    { id: string; data: DeleteTreatmentPlanDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return invoiceControllerDeleteTreatmentPlan(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceControllerDeleteTreatmentPlanMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerDeleteTreatmentPlan>>
>;
export type InvoiceControllerDeleteTreatmentPlanMutationBody = DeleteTreatmentPlanDto;
export type InvoiceControllerDeleteTreatmentPlanMutationError = unknown;

/**
 * @summary required permisson: delete_invoice
 */
export const useInvoiceControllerDeleteTreatmentPlan = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceControllerDeleteTreatmentPlan>>,
      TError,
      { id: string; data: DeleteTreatmentPlanDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceControllerDeleteTreatmentPlan>>,
  TError,
  { id: string; data: DeleteTreatmentPlanDto },
  TContext
> => {
  const mutationOptions = getInvoiceControllerDeleteTreatmentPlanMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_invoice
 */
export const invoiceControllerRecalculate = (id: string) => {
  return apiInstance<InvoiceControllerRecalculate200>({
    url: `/api/invoices/${id}/recalculate`,
    method: 'PUT',
  });
};

export const getInvoiceControllerRecalculateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceControllerRecalculate>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceControllerRecalculate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['invoiceControllerRecalculate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceControllerRecalculate>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return invoiceControllerRecalculate(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceControllerRecalculateMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerRecalculate>>
>;

export type InvoiceControllerRecalculateMutationError = unknown;

/**
 * @summary required permisson: update_invoice
 */
export const useInvoiceControllerRecalculate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceControllerRecalculate>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceControllerRecalculate>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getInvoiceControllerRecalculateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_invoice
 */
export const invoiceControllerGetLoanAmount = (id: string, signal?: AbortSignal) => {
  return apiInstance<void>({ url: `/api/invoices/${id}/loan-amount`, method: 'GET', signal });
};

export const getInvoiceControllerGetLoanAmountQueryKey = (id?: string) => {
  return [`/api/invoices/${id}/loan-amount`] as const;
};

export const getInvoiceControllerGetLoanAmountQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerGetLoanAmountQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>> = ({
    signal,
  }) => invoiceControllerGetLoanAmount(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerGetLoanAmountQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>
>;
export type InvoiceControllerGetLoanAmountQueryError = unknown;

export function useInvoiceControllerGetLoanAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerGetLoanAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerGetLoanAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_invoice
 */

export function useInvoiceControllerGetLoanAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanAmount>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerGetLoanAmountQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_invoice
 */
export const invoiceControllerGetCashAmount = (id: string, signal?: AbortSignal) => {
  return apiInstance<void>({ url: `/api/invoices/${id}/cash-amount`, method: 'GET', signal });
};

export const getInvoiceControllerGetCashAmountQueryKey = (id?: string) => {
  return [`/api/invoices/${id}/cash-amount`] as const;
};

export const getInvoiceControllerGetCashAmountQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerGetCashAmountQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>> = ({
    signal,
  }) => invoiceControllerGetCashAmount(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerGetCashAmountQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>
>;
export type InvoiceControllerGetCashAmountQueryError = unknown;

export function useInvoiceControllerGetCashAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerGetCashAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerGetCashAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_invoice
 */

export function useInvoiceControllerGetCashAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetCashAmount>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerGetCashAmountQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_invoice
 */
export const invoiceControllerGetChequeAmount = (id: string, signal?: AbortSignal) => {
  return apiInstance<void>({ url: `/api/invoices/${id}/cheque-amount`, method: 'GET', signal });
};

export const getInvoiceControllerGetChequeAmountQueryKey = (id?: string) => {
  return [`/api/invoices/${id}/cheque-amount`] as const;
};

export const getInvoiceControllerGetChequeAmountQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerGetChequeAmountQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>> = ({
    signal,
  }) => invoiceControllerGetChequeAmount(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerGetChequeAmountQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>
>;
export type InvoiceControllerGetChequeAmountQueryError = unknown;

export function useInvoiceControllerGetChequeAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerGetChequeAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerGetChequeAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_invoice
 */

export function useInvoiceControllerGetChequeAmount<
  TData = Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetChequeAmount>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerGetChequeAmountQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_invoice
 */
export const invoiceControllerGetLoanInfo = (id: string, signal?: AbortSignal) => {
  return apiInstance<void>({ url: `/api/invoices/${id}/loan-info`, method: 'GET', signal });
};

export const getInvoiceControllerGetLoanInfoQueryKey = (id?: string) => {
  return [`/api/invoices/${id}/loan-info`] as const;
};

export const getInvoiceControllerGetLoanInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInvoiceControllerGetLoanInfoQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>> = ({
    signal,
  }) => invoiceControllerGetLoanInfo(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InvoiceControllerGetLoanInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>
>;
export type InvoiceControllerGetLoanInfoQueryError = unknown;

export function useInvoiceControllerGetLoanInfo<
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerGetLoanInfo<
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>,
          TError,
          Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInvoiceControllerGetLoanInfo<
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_invoice
 */

export function useInvoiceControllerGetLoanInfo<
  TData = Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof invoiceControllerGetLoanInfo>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInvoiceControllerGetLoanInfoQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
