/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreateDentColorDto,
  DentColor,
  DentColorsControllerFindAllParams,
  DentColorsControllerUpdate200,
  UpdateDentColorDto,
} from '../../models';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

export const dentColorsControllerCreate = (
  createDentColorDto: CreateDentColorDto,
  signal?: AbortSignal
) => {
  return apiInstance<DentColor>({
    url: `/api/dent-colors`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createDentColorDto,
    signal,
  });
};

export const getDentColorsControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dentColorsControllerCreate>>,
    TError,
    { data: CreateDentColorDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dentColorsControllerCreate>>,
  TError,
  { data: CreateDentColorDto },
  TContext
> => {
  const mutationKey = ['dentColorsControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dentColorsControllerCreate>>,
    { data: CreateDentColorDto }
  > = (props) => {
    const { data } = props ?? {};

    return dentColorsControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DentColorsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dentColorsControllerCreate>>
>;
export type DentColorsControllerCreateMutationBody = CreateDentColorDto;
export type DentColorsControllerCreateMutationError = unknown;

export const useDentColorsControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dentColorsControllerCreate>>,
      TError,
      { data: CreateDentColorDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof dentColorsControllerCreate>>,
  TError,
  { data: CreateDentColorDto },
  TContext
> => {
  const mutationOptions = getDentColorsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const dentColorsControllerFindAll = (
  params?: DentColorsControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<DentColor[]>({ url: `/api/dent-colors`, method: 'GET', params, signal });
};

export const getDentColorsControllerFindAllQueryKey = (
  params?: DentColorsControllerFindAllParams
) => {
  return [`/api/dent-colors`, ...(params ? [params] : [])] as const;
};

export const getDentColorsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof dentColorsControllerFindAll>>,
  TError = unknown,
>(
  params?: DentColorsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDentColorsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dentColorsControllerFindAll>>> = ({
    signal,
  }) => dentColorsControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dentColorsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DentColorsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof dentColorsControllerFindAll>>
>;
export type DentColorsControllerFindAllQueryError = unknown;

export function useDentColorsControllerFindAll<
  TData = Awaited<ReturnType<typeof dentColorsControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | DentColorsControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dentColorsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof dentColorsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDentColorsControllerFindAll<
  TData = Awaited<ReturnType<typeof dentColorsControllerFindAll>>,
  TError = unknown,
>(
  params?: DentColorsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dentColorsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof dentColorsControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDentColorsControllerFindAll<
  TData = Awaited<ReturnType<typeof dentColorsControllerFindAll>>,
  TError = unknown,
>(
  params?: DentColorsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDentColorsControllerFindAll<
  TData = Awaited<ReturnType<typeof dentColorsControllerFindAll>>,
  TError = unknown,
>(
  params?: DentColorsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDentColorsControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const dentColorsControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<DentColor>({ url: `/api/dent-colors/${id}`, method: 'GET', signal });
};

export const getDentColorsControllerFindOneQueryKey = (id?: string) => {
  return [`/api/dent-colors/${id}`] as const;
};

export const getDentColorsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof dentColorsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getDentColorsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof dentColorsControllerFindOne>>> = ({
    signal,
  }) => dentColorsControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof dentColorsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type DentColorsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof dentColorsControllerFindOne>>
>;
export type DentColorsControllerFindOneQueryError = unknown;

export function useDentColorsControllerFindOne<
  TData = Awaited<ReturnType<typeof dentColorsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof dentColorsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof dentColorsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDentColorsControllerFindOne<
  TData = Awaited<ReturnType<typeof dentColorsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof dentColorsControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof dentColorsControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useDentColorsControllerFindOne<
  TData = Awaited<ReturnType<typeof dentColorsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useDentColorsControllerFindOne<
  TData = Awaited<ReturnType<typeof dentColorsControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof dentColorsControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getDentColorsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const dentColorsControllerUpdate = (id: string, updateDentColorDto: UpdateDentColorDto) => {
  return apiInstance<DentColorsControllerUpdate200>({
    url: `/api/dent-colors/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updateDentColorDto,
  });
};

export const getDentColorsControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dentColorsControllerUpdate>>,
    TError,
    { id: string; data: UpdateDentColorDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dentColorsControllerUpdate>>,
  TError,
  { id: string; data: UpdateDentColorDto },
  TContext
> => {
  const mutationKey = ['dentColorsControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dentColorsControllerUpdate>>,
    { id: string; data: UpdateDentColorDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return dentColorsControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type DentColorsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof dentColorsControllerUpdate>>
>;
export type DentColorsControllerUpdateMutationBody = UpdateDentColorDto;
export type DentColorsControllerUpdateMutationError = unknown;

export const useDentColorsControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dentColorsControllerUpdate>>,
      TError,
      { id: string; data: UpdateDentColorDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof dentColorsControllerUpdate>>,
  TError,
  { id: string; data: UpdateDentColorDto },
  TContext
> => {
  const mutationOptions = getDentColorsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
export const dentColorsControllerRemove = (id: string) => {
  return apiInstance<void>({ url: `/api/dent-colors/${id}`, method: 'DELETE' });
};

export const getDentColorsControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof dentColorsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof dentColorsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['dentColorsControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof dentColorsControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return dentColorsControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type DentColorsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof dentColorsControllerRemove>>
>;

export type DentColorsControllerRemoveMutationError = unknown;

export const useDentColorsControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof dentColorsControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof dentColorsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getDentColorsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
