/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { InventoryControllerFindAllParams } from '../../models';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

export const inventoryControllerFindAll = (
  params?: InventoryControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<void>({ url: `/api/inventory`, method: 'GET', params, signal });
};

export const getInventoryControllerFindAllQueryKey = (
  params?: InventoryControllerFindAllParams
) => {
  return [`/api/inventory`, ...(params ? [params] : [])] as const;
};

export const getInventoryControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
  TError = unknown,
>(
  params?: InventoryControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getInventoryControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof inventoryControllerFindAll>>> = ({
    signal,
  }) => inventoryControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof inventoryControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InventoryControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof inventoryControllerFindAll>>
>;
export type InventoryControllerFindAllQueryError = unknown;

export function useInventoryControllerFindAll<
  TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | InventoryControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof inventoryControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof inventoryControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInventoryControllerFindAll<
  TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
  TError = unknown,
>(
  params?: InventoryControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof inventoryControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof inventoryControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useInventoryControllerFindAll<
  TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
  TError = unknown,
>(
  params?: InventoryControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useInventoryControllerFindAll<
  TData = Awaited<ReturnType<typeof inventoryControllerFindAll>>,
  TError = unknown,
>(
  params?: InventoryControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof inventoryControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getInventoryControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
