/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  CreatePatientGroupDto,
  PatientGroup,
  PatientGroupControllerFindAllParams,
  SetGroupPatientsDto,
  UpdatePatientGroupDto,
} from '../../models1';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: create_patient
 */
export const patientGroupControllerCreate = (
  createPatientGroupDto: CreatePatientGroupDto,
  signal?: AbortSignal
) => {
  return apiInstance<PatientGroup>({
    url: `/api/patient-groups`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: createPatientGroupDto,
    signal,
  });
};

export const getPatientGroupControllerCreateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patientGroupControllerCreate>>,
    TError,
    { data: CreatePatientGroupDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patientGroupControllerCreate>>,
  TError,
  { data: CreatePatientGroupDto },
  TContext
> => {
  const mutationKey = ['patientGroupControllerCreate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patientGroupControllerCreate>>,
    { data: CreatePatientGroupDto }
  > = (props) => {
    const { data } = props ?? {};

    return patientGroupControllerCreate(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatientGroupControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof patientGroupControllerCreate>>
>;
export type PatientGroupControllerCreateMutationBody = CreatePatientGroupDto;
export type PatientGroupControllerCreateMutationError = unknown;

/**
 * @summary required permisson: create_patient
 */
export const usePatientGroupControllerCreate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patientGroupControllerCreate>>,
      TError,
      { data: CreatePatientGroupDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patientGroupControllerCreate>>,
  TError,
  { data: CreatePatientGroupDto },
  TContext
> => {
  const mutationOptions = getPatientGroupControllerCreateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: read_patient
 */
export const patientGroupControllerFindAll = (
  params?: PatientGroupControllerFindAllParams,
  signal?: AbortSignal
) => {
  return apiInstance<PatientGroup[]>({ url: `/api/patient-groups`, method: 'GET', params, signal });
};

export const getPatientGroupControllerFindAllQueryKey = (
  params?: PatientGroupControllerFindAllParams
) => {
  return [`/api/patient-groups`, ...(params ? [params] : [])] as const;
};

export const getPatientGroupControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof patientGroupControllerFindAll>>,
  TError = unknown,
>(
  params?: PatientGroupControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindAll>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPatientGroupControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof patientGroupControllerFindAll>>> = ({
    signal,
  }) => patientGroupControllerFindAll(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof patientGroupControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatientGroupControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof patientGroupControllerFindAll>>
>;
export type PatientGroupControllerFindAllQueryError = unknown;

export function usePatientGroupControllerFindAll<
  TData = Awaited<ReturnType<typeof patientGroupControllerFindAll>>,
  TError = unknown,
>(
  params: undefined | PatientGroupControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindAll>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientGroupControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof patientGroupControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePatientGroupControllerFindAll<
  TData = Awaited<ReturnType<typeof patientGroupControllerFindAll>>,
  TError = unknown,
>(
  params?: PatientGroupControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindAll>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientGroupControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof patientGroupControllerFindAll>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePatientGroupControllerFindAll<
  TData = Awaited<ReturnType<typeof patientGroupControllerFindAll>>,
  TError = unknown,
>(
  params?: PatientGroupControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_patient
 */

export function usePatientGroupControllerFindAll<
  TData = Awaited<ReturnType<typeof patientGroupControllerFindAll>>,
  TError = unknown,
>(
  params?: PatientGroupControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindAll>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPatientGroupControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: read_patient
 */
export const patientGroupControllerFindOne = (id: string, signal?: AbortSignal) => {
  return apiInstance<PatientGroup>({ url: `/api/patient-groups/${id}`, method: 'GET', signal });
};

export const getPatientGroupControllerFindOneQueryKey = (id?: string) => {
  return [`/api/patient-groups/${id}`] as const;
};

export const getPatientGroupControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof patientGroupControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindOne>>, TError, TData>
    >;
  }
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPatientGroupControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof patientGroupControllerFindOne>>> = ({
    signal,
  }) => patientGroupControllerFindOne(id, signal);

  return { queryKey, queryFn, enabled: !!id, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof patientGroupControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PatientGroupControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof patientGroupControllerFindOne>>
>;
export type PatientGroupControllerFindOneQueryError = unknown;

export function usePatientGroupControllerFindOne<
  TData = Awaited<ReturnType<typeof patientGroupControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindOne>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientGroupControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof patientGroupControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePatientGroupControllerFindOne<
  TData = Awaited<ReturnType<typeof patientGroupControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindOne>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof patientGroupControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof patientGroupControllerFindOne>>
        >,
        'initialData'
      >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePatientGroupControllerFindOne<
  TData = Awaited<ReturnType<typeof patientGroupControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
/**
 * @summary required permisson: read_patient
 */

export function usePatientGroupControllerFindOne<
  TData = Awaited<ReturnType<typeof patientGroupControllerFindOne>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof patientGroupControllerFindOne>>, TError, TData>
    >;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPatientGroupControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * @summary required permisson: update_patient
 */
export const patientGroupControllerUpdate = (
  id: string,
  updatePatientGroupDto: UpdatePatientGroupDto
) => {
  return apiInstance<PatientGroup>({
    url: `/api/patient-groups/${id}`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: updatePatientGroupDto,
  });
};

export const getPatientGroupControllerUpdateMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patientGroupControllerUpdate>>,
    TError,
    { id: string; data: UpdatePatientGroupDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patientGroupControllerUpdate>>,
  TError,
  { id: string; data: UpdatePatientGroupDto },
  TContext
> => {
  const mutationKey = ['patientGroupControllerUpdate'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patientGroupControllerUpdate>>,
    { id: string; data: UpdatePatientGroupDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return patientGroupControllerUpdate(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatientGroupControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof patientGroupControllerUpdate>>
>;
export type PatientGroupControllerUpdateMutationBody = UpdatePatientGroupDto;
export type PatientGroupControllerUpdateMutationError = unknown;

/**
 * @summary required permisson: update_patient
 */
export const usePatientGroupControllerUpdate = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patientGroupControllerUpdate>>,
      TError,
      { id: string; data: UpdatePatientGroupDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patientGroupControllerUpdate>>,
  TError,
  { id: string; data: UpdatePatientGroupDto },
  TContext
> => {
  const mutationOptions = getPatientGroupControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: delete_patient
 */
export const patientGroupControllerRemove = (id: string) => {
  return apiInstance<void>({ url: `/api/patient-groups/${id}`, method: 'DELETE' });
};

export const getPatientGroupControllerRemoveMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patientGroupControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patientGroupControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ['patientGroupControllerRemove'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patientGroupControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return patientGroupControllerRemove(id);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatientGroupControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof patientGroupControllerRemove>>
>;

export type PatientGroupControllerRemoveMutationError = unknown;

/**
 * @summary required permisson: delete_patient
 */
export const usePatientGroupControllerRemove = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patientGroupControllerRemove>>,
      TError,
      { id: string },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patientGroupControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getPatientGroupControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_patient
 */
export const patientGroupControllerAddPatients = (
  id: string,
  setGroupPatientsDto: SetGroupPatientsDto,
  signal?: AbortSignal
) => {
  return apiInstance<PatientGroup>({
    url: `/api/patient-groups/${id}/patients`,
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    data: setGroupPatientsDto,
    signal,
  });
};

export const getPatientGroupControllerAddPatientsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patientGroupControllerAddPatients>>,
    TError,
    { id: string; data: SetGroupPatientsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patientGroupControllerAddPatients>>,
  TError,
  { id: string; data: SetGroupPatientsDto },
  TContext
> => {
  const mutationKey = ['patientGroupControllerAddPatients'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patientGroupControllerAddPatients>>,
    { id: string; data: SetGroupPatientsDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return patientGroupControllerAddPatients(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatientGroupControllerAddPatientsMutationResult = NonNullable<
  Awaited<ReturnType<typeof patientGroupControllerAddPatients>>
>;
export type PatientGroupControllerAddPatientsMutationBody = SetGroupPatientsDto;
export type PatientGroupControllerAddPatientsMutationError = unknown;

/**
 * @summary required permisson: update_patient
 */
export const usePatientGroupControllerAddPatients = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patientGroupControllerAddPatients>>,
      TError,
      { id: string; data: SetGroupPatientsDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patientGroupControllerAddPatients>>,
  TError,
  { id: string; data: SetGroupPatientsDto },
  TContext
> => {
  const mutationOptions = getPatientGroupControllerAddPatientsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_patient
 */
export const patientGroupControllerRemovePatients = (
  id: string,
  setGroupPatientsDto: SetGroupPatientsDto
) => {
  return apiInstance<PatientGroup>({
    url: `/api/patient-groups/${id}/patients`,
    method: 'DELETE',
    headers: { 'Content-Type': 'application/json' },
    data: setGroupPatientsDto,
  });
};

export const getPatientGroupControllerRemovePatientsMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof patientGroupControllerRemovePatients>>,
    TError,
    { id: string; data: SetGroupPatientsDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof patientGroupControllerRemovePatients>>,
  TError,
  { id: string; data: SetGroupPatientsDto },
  TContext
> => {
  const mutationKey = ['patientGroupControllerRemovePatients'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof patientGroupControllerRemovePatients>>,
    { id: string; data: SetGroupPatientsDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return patientGroupControllerRemovePatients(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PatientGroupControllerRemovePatientsMutationResult = NonNullable<
  Awaited<ReturnType<typeof patientGroupControllerRemovePatients>>
>;
export type PatientGroupControllerRemovePatientsMutationBody = SetGroupPatientsDto;
export type PatientGroupControllerRemovePatientsMutationError = unknown;

/**
 * @summary required permisson: update_patient
 */
export const usePatientGroupControllerRemovePatients = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof patientGroupControllerRemovePatients>>,
      TError,
      { id: string; data: SetGroupPatientsDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof patientGroupControllerRemovePatients>>,
  TError,
  { id: string; data: SetGroupPatientsDto },
  TContext
> => {
  const mutationOptions = getPatientGroupControllerRemovePatientsMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
