/**
 * Generated by orval v7.14.0 🍺
 * Do not edit manually.
 * clinic reservation system api
 * OpenAPI spec version: 2.0.0
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { AttachSpecialDiscount, UpdatePaymentMethodDto } from '../../models2';

import { apiInstance } from '../../../swaggerConfig/apiInstance';

/**
 * @summary required permisson: update_invoice_item
 */
export const invoiceItemControllerUpdatePaymentMethod = (
  id: string,
  updatePaymentMethodDto: UpdatePaymentMethodDto
) => {
  return apiInstance<void>({
    url: `/api/invoice-items/${id}/payment-method`,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    data: updatePaymentMethodDto,
  });
};

export const getInvoiceItemControllerUpdatePaymentMethodMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceItemControllerUpdatePaymentMethod>>,
    TError,
    { id: string; data: UpdatePaymentMethodDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceItemControllerUpdatePaymentMethod>>,
  TError,
  { id: string; data: UpdatePaymentMethodDto },
  TContext
> => {
  const mutationKey = ['invoiceItemControllerUpdatePaymentMethod'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceItemControllerUpdatePaymentMethod>>,
    { id: string; data: UpdatePaymentMethodDto }
  > = (props) => {
    const { id, data } = props ?? {};

    return invoiceItemControllerUpdatePaymentMethod(id, data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceItemControllerUpdatePaymentMethodMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceItemControllerUpdatePaymentMethod>>
>;
export type InvoiceItemControllerUpdatePaymentMethodMutationBody = UpdatePaymentMethodDto;
export type InvoiceItemControllerUpdatePaymentMethodMutationError = unknown;

/**
 * @summary required permisson: update_invoice_item
 */
export const useInvoiceItemControllerUpdatePaymentMethod = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceItemControllerUpdatePaymentMethod>>,
      TError,
      { id: string; data: UpdatePaymentMethodDto },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceItemControllerUpdatePaymentMethod>>,
  TError,
  { id: string; data: UpdatePaymentMethodDto },
  TContext
> => {
  const mutationOptions = getInvoiceItemControllerUpdatePaymentMethodMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_invoice_item
 */
export const invoiceItemControllerAttachSpecialDiscount = (
  attachSpecialDiscount: AttachSpecialDiscount
) => {
  return apiInstance<void>({
    url: `/api/invoice-items/attach-special-discount`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: attachSpecialDiscount,
  });
};

export const getInvoiceItemControllerAttachSpecialDiscountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceItemControllerAttachSpecialDiscount>>,
    TError,
    { data: AttachSpecialDiscount },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceItemControllerAttachSpecialDiscount>>,
  TError,
  { data: AttachSpecialDiscount },
  TContext
> => {
  const mutationKey = ['invoiceItemControllerAttachSpecialDiscount'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceItemControllerAttachSpecialDiscount>>,
    { data: AttachSpecialDiscount }
  > = (props) => {
    const { data } = props ?? {};

    return invoiceItemControllerAttachSpecialDiscount(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceItemControllerAttachSpecialDiscountMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceItemControllerAttachSpecialDiscount>>
>;
export type InvoiceItemControllerAttachSpecialDiscountMutationBody = AttachSpecialDiscount;
export type InvoiceItemControllerAttachSpecialDiscountMutationError = unknown;

/**
 * @summary required permisson: update_invoice_item
 */
export const useInvoiceItemControllerAttachSpecialDiscount = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceItemControllerAttachSpecialDiscount>>,
      TError,
      { data: AttachSpecialDiscount },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceItemControllerAttachSpecialDiscount>>,
  TError,
  { data: AttachSpecialDiscount },
  TContext
> => {
  const mutationOptions = getInvoiceItemControllerAttachSpecialDiscountMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * @summary required permisson: update_invoice_item
 */
export const invoiceItemControllerRemoveSpecialDiscount = (
  attachSpecialDiscount: AttachSpecialDiscount
) => {
  return apiInstance<void>({
    url: `/api/invoice-items/remove-special-discount`,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    data: attachSpecialDiscount,
  });
};

export const getInvoiceItemControllerRemoveSpecialDiscountMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof invoiceItemControllerRemoveSpecialDiscount>>,
    TError,
    { data: AttachSpecialDiscount },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof invoiceItemControllerRemoveSpecialDiscount>>,
  TError,
  { data: AttachSpecialDiscount },
  TContext
> => {
  const mutationKey = ['invoiceItemControllerRemoveSpecialDiscount'];
  const { mutation: mutationOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof invoiceItemControllerRemoveSpecialDiscount>>,
    { data: AttachSpecialDiscount }
  > = (props) => {
    const { data } = props ?? {};

    return invoiceItemControllerRemoveSpecialDiscount(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type InvoiceItemControllerRemoveSpecialDiscountMutationResult = NonNullable<
  Awaited<ReturnType<typeof invoiceItemControllerRemoveSpecialDiscount>>
>;
export type InvoiceItemControllerRemoveSpecialDiscountMutationBody = AttachSpecialDiscount;
export type InvoiceItemControllerRemoveSpecialDiscountMutationError = unknown;

/**
 * @summary required permisson: update_invoice_item
 */
export const useInvoiceItemControllerRemoveSpecialDiscount = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof invoiceItemControllerRemoveSpecialDiscount>>,
      TError,
      { data: AttachSpecialDiscount },
      TContext
    >;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof invoiceItemControllerRemoveSpecialDiscount>>,
  TError,
  { data: AttachSpecialDiscount },
  TContext
> => {
  const mutationOptions = getInvoiceItemControllerRemoveSpecialDiscountMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
